apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcs.fullname" . }}-secrets
type: Opaque
data:
  gcs_key_id: {{ .Values.mcs.gcs.key_id | b64enc }}
  gcs_secret: {{ .Values.mcs.gcs.secret | b64enc }}