---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  # for now this application is a single process + thread
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app.fullname" . }}
      {{- with .Values.app.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image.repo }}:{{ .Values.app.image.tag }}
        {{- with .Values.app.command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.app.args }}
        args: {{ toYaml .Values.app.args | nindent 10 }} 
        {{- end }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        {{- with .Values.app.resources }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.app.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          - name: {{ .Values.app.hostEnvVar }}
            value: "{{ .Values.app.host }}"
          - name: {{ .Values.app.portEnvVar }}
            value: "{{ .Values.app.port }}"
          {{- range $key, $value := .Values.app.envVars }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range .Values.app.rawEnvVars }}
            {{- toYaml . | nindent 12 }}
          {{ end }}
      {{- with .Values.app.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}