{{- if .Values.app.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- toYaml .Values.app.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.app.ingress.className }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "app.fullname" . }}
            port:
              number: {{ .Values.app.port }}
{{ end }}