---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- toYaml .Values.app.service.annotations | nindent 4 }}
spec:
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}