apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
    - name: certificates
    - name: operators
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./ops/k8s-apps/production
  force: true
  prune: true
  wait: true
  images:
    - name: ghcr.io/opensource-observer/oso
      newName: ghcr.io/opensource-observer/oso # {"$imagepolicy": "flux-system:oso:name"}
      newTag: deploy-20250605223104-01a4623 # {"$imagepolicy": "flux-system:oso:tag"}
