packages:
  - "apps/docs"
  - "apps/frontend"
  - "apps/hasura-clickhouse"
  - "lib/oss-artifact-validators"
  - "lib/utils"
  - "lib/ycb"
  - "ops/external-prs"
  - "ops/github-app-utils"
  - "warehouse/cube"
