apiVersion: v1
kind: Namespace
metadata:
  name: base-trino
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
    opensource.observer/cert-inject: "enabled"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trino
  namespace: base-trino
spec:
  interval: 5m
  url: https://trinodb.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trino
  namespace: base-trino
spec:
  chart:
    spec:
      chart: trino
      version: "1.37.0"
      sourceRef:
        kind: HelmRepository
        name: trino
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: true
      name: base-trino
    coordinator:
      additionalVolumes:
        - name: cluster-self-signed-bundle
          configMap:
            name: cluster-self-signed-bundle
            defaultMode: 0644
            optional: false
            items:
            - key: ca-certificates.crt
              path: ca-certificates.crt
            - key: ca-certificates.p12
              path: ca-certificates.p12
      additionalVolumeMounts:
        - name: cluster-self-signed-bundle
          mountPath: /etc/ssl/k8s-certs
      additionalJVMConfig:
        #- "--add-opens=java.base/java.nio=ALL-UNNAMED"
        - "-Djavax.net.ssl.trustStore=/etc/ssl/k8s-certs/ca-certificates.p12"
      
    worker:
      additionalVolumes:
        - name: cluster-self-signed-bundle
          configMap:
            name: cluster-self-signed-bundle
            defaultMode: 0644
            optional: false
            items:
            - key: ca-certificates.crt
              path: ca-certificates.crt
            - key: ca-certificates.p12
              path: ca-certificates.p12
      additionalVolumeMounts:
        - name: cluster-self-signed-bundle
          mountPath: /etc/ssl/k8s-certs
      additionalJVMConfig:
        #- "--add-opens=java.base/java.nio=ALL-UNNAMED"
        - "-Djavax.net.ssl.trustStore=/etc/ssl/k8s-certs/ca-certificates.p12"
