apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/trino
namespace: production-consumer-trino
patches:
  - path: ./custom-helm-values.yaml
    target:
      kind: HelmRelease
    options:
      allowNameChange: true