apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-access-control
data:
  rules.json: |
    {
      "catalogs": [
        {
          "user": "admin",
          "allow": "owner"
        },
        {
          "catalog": "system",
          "allow": "none"
        },
        {
          "user": "rw-*",
          "allow": "all"
        },
        {
          "user": "ro-*",
          "allow": "read-only"
        },
        {
          "user": "jwt-.*",
          "allow": "read-only"
        },
        {
          "user": "user",
          "allow": "read-only"
        },
        {
          "allow": "all"
        }
      ]
    }
