apiVersion: v1
kind: Namespace
metadata:
  name: base-mcp
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcp
  namespace: base-mcp
spec:
  chart:
    spec:
      chart: ./ops/helm-charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    app:
      name: "oso-mcp"
      command: ["uv"]
      args: 
        - run
        - --directory
        - warehouse/oso_mcp 
        - mcp
        - serve
      hostEnvVar: "MCP_HOST"
      portEnvVar: "MCP_PORT"

