CREATE SCHEMA IF NOT EXISTS bigquery.defillama;

CREATE TABLE IF NOT EXISTS bigquery.defillama.tvl (
    id varchar,
    name varchar,
    address varchar,
    symbol varchar,
    url varchar,
    description varchar,
    chain varchar,
    logo varchar,
    audits varchar,
    category varchar,
    chains json,
    module varchar,
    oracles json,
    forked_from json,
    twitter varchar,
    parent_protocol varchar,
    listed_at bigint,
    chain_tvls json,
    tvl json,
    tokens_in_usd json,
    tokens json,
    current_chain_tvls json,
    raises json,
    metrics json,
    other_protocols json,
    methodology varchar,
    _dlt_load_id varchar,
    _dlt_id varchar,
    audit_links json,
    misrepresented_tokens boolean,
    language varchar,
    tokens_excluded_from_parent json,
    hallmarks json,
    gecko_id varchar,
    mcap double,
    wrong_liquidity boolean,
    oracles_by_chain json,
    github json,
    cmc_id varchar,
    oracles_breakdown json,
    asset_token varchar,
    treasury varchar,
    stablecoins json,
    governance_id json,
    previous_names json,
    referral_url varchar,
    audit_note varchar,
    _protocols_name varchar,
    slug varchar
);

INSERT INTO
    bigquery.defillama.tvl (
        id,
        name,
        address,
        symbol,
        url,
        description,
        chain,
        logo,
        audits,
        category,
        chains,
        module,
        oracles,
        forked_from,
        twitter,
        parent_protocol,
        listed_at,
        chain_tvls,
        tvl,
        tokens_in_usd,
        tokens,
        current_chain_tvls,
        raises,
        metrics,
        other_protocols,
        methodology,
        _dlt_load_id,
        _dlt_id,
        audit_links,
        misrepresented_tokens,
        language,
        tokens_excluded_from_parent,
        hallmarks,
        gecko_id,
        mcap,
        wrong_liquidity,
        oracles_by_chain,
        github,
        cmc_id,
        oracles_breakdown,
        asset_token,
        treasury,
        stablecoins,
        governance_id,
        previous_names,
        referral_url,
        audit_note,
        _protocols_name,
        slug
    )
VALUES
    (
        '1',
        'Protocol A',
        '0x123',
        'PA',
        'https://protocol-a.com',
        'Description A',
        'Ethereum',
        'https://logo-a.com',
        'Audit A',
        'DeFi',
        json_parse('["Ethereum"]'),
        'module-a',
        json_parse('["Oracle A"]'),
        json_parse('["Fork A"]'),
        '@protocol_a',
        'Parent A',
        1622548800,
        json_parse('{"BSC":{"tokens":[],"tokensInUsd":[],"tvl":[{"date":1677283200,"totalLiquidityUSD":0}]}}'),
        json_parse('{"total": 1000000}'),
        json_parse('{"tokenA": 500000, "tokenB": 500000}'),
        json_parse('["tokenA", "tokenB"]'),
        json_parse('{"Ethereum": 1000000}'),
        json_parse('[]'),
        json_parse('[]'),
        json_parse('[]'),
        'Methodology A',
        '1',
        'id_1',
        json_parse('["https://audit-a.com"]'),
        false,
        'en',
        json_parse('[]'),
        json_parse('[]'),
        'gecko_id_a',
        1000000.0,
        false,
        json_parse('["Oracle A"]'),
        json_parse('["https://github.com/protocol_a"]'),
        'cmc_id_a',
        json_parse('["Oracle Breakdown A"]'),
        'asset_token_a',
        'treasury_a',
        json_parse('["stablecoinA"]'),
        json_parse('["governance_id_a"]'),
        json_parse('["Previous Name A"]'),
        'https://referral-a.com',
        'Audit Note A',
        'protocols_name_a',
        'slug_a'
    ),
    (
        '2',
        'Protocol B',
        '0x456',
        'PB',
        'https://protocol-b.com',
        'Description B',
        'Binance Smart Chain',
        'https://logo-b.com',
        'Audit B',
        'DeFi',
        json_parse('["Binance Smart Chain"]'),
        'module-b',
        json_parse('["Oracle B"]'),
        json_parse('["Fork B"]'),
        '@protocol_b',
        'Parent B',
        1625130800,
        json_parse('{"BSC":{"tokens":[],"tokensInUsd":[],"tvl":[{"date":1677283200,"totalLiquidityUSD":0}]}}'),
        json_parse('{"total": 2000000}'),
        json_parse('{"tokenC": 1000000, "tokenD": 1000000}'),
        json_parse('["tokenC", "tokenD"]'),
        json_parse('{"Binance Smart Chain": 2000000}'),
        json_parse('[]'),
        json_parse('[]'),
        json_parse('[]'),
        'Methodology B',
        '2',
        'id_2',
        json_parse('["https://audit-b.com"]'),
        false,
        'en',
        json_parse('[]'),
        json_parse('[]'),
        'gecko_id_b',
        2000000.0,
        false,
        json_parse('["Oracle B"]'),
        json_parse('["https://github.com/protocol_b"]'),
        'cmc_id_b',
        json_parse('["Oracle Breakdown B"]'),
        'asset_token_b',
        'treasury_b',
        json_parse('["stablecoinB"]'),
        json_parse('["governance_id_b"]'),
        json_parse('["Previous Name B"]'),
        'https://referral-b.com',
        'Audit Note B',
        'protocols_name_b',
        'slug_b'
    );