---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  labels:
    toolkit.fluxcd.io/tenant: ops
    opensource.observer/cert-inject: "enabled"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio-operator
spec:
  interval: 24h
  url: https://operator.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mini-operator 
  namespace: minio-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: "6.0.4"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio-operator
      interval: 1h
  values:
    operator:
      replicaCount: 1