apiVersion: v1
kind: Namespace
metadata:
  name: production-scheduler
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
