from sqlalchemy.sql import sqltypes
from trino.sqlalchemy import compiler
from trino.sqlalchemy.datatype import JSONIndexType, JSONPathType
from trino.sqlalchemy.dialect import TrinoDialect as TrinoDialectBase

from . import dbapi

colspecs = {
    sqltypes.JSON.JSONIndexType: JSONIndexType,
    sqltypes.JSON.JSONPathType: JSONPathType,
}


class TrinoDialect(TrinoDialectBase):
    name = "trinoso"
    driver = "rest"

    statement_compiler = compiler.TrinoSQLCompiler
    ddl_compiler = compiler.TrinoDDLCompiler
    type_compiler = compiler.TrinoTypeCompiler
    preparer = compiler.TrinoIdentifierPreparer

    # Data Type
    supports_native_enum = False
    supports_native_boolean = True
    supports_native_decimal = True

    # Column options
    supports_sequences = False
    supports_comments = True
    inline_comments = True
    supports_default_values = False

    # DDL
    supports_alter = True

    # DML
    # Queries of the form `INSERT () VALUES ()` is not supported by Trino.
    supports_empty_insert = False
    supports_multivalues_insert = True
    postfetch_lastrowid = False

    # Caching
    # Warnings are generated by SQLAlchmey if this flag is not explicitly set
    # and tests are needed before being enabled
    supports_statement_cache = False

    # Support proper ordering of CTEs in regard to an INSERT statement
    cte_follows_insert = True
    colspecs = colspecs

    @classmethod
    def dbapi(cls):  # type: ignore
        """
        ref: https://www.python.org/dev/peps/pep-0249/#module-interface
        """
        return dbapi

    @classmethod
    def import_dbapi(cls):  # type: ignore
        """
        ref: https://www.python.org/dev/peps/pep-0249/#module-interface
        """
        return dbapi
