from datetime import datetime

from metrics_tools.seed.types import Column, SeedConfig
from pydantic import BaseModel


class Accounts(BaseModel):
    id: str = Column("VARCHAR")
    legacy_id: int | None = Column("INTEGER")
    slug: str | None = Column("VARCHAR")
    type: str | None = Column("VARCHAR")
    name: str | None = Column("VARCHAR")
    long_description: str | None = Column("VARCHAR")
    social_links: str | None = Column("JSON")
    currency: str | None = Column("VARCHAR")
    expense_policy: str | None = Column("VARCHAR")
    is_verified: bool | None = Column("BOOLEAN")
    is_incognito: bool | None = Column("BOOLEAN")
    image_url: str | None = Column("VARCHAR")
    created_at: datetime | None = Column("TIMESTAMP")
    updated_at: datetime | None = Column("TIMESTAMP")
    is_archived: bool | None = Column("BOOLEAN")
    is_frozen: bool | None = Column("BOOLEAN")
    is_suspended: bool | None = Column("BOOLEAN")
    is_active: bool | None = Column("BOOLEAN")
    is_host: bool | None = Column("BOOLEAN")
    is_admin: bool | None = Column("BOOLEAN")
    settings: str | None = Column("JSON")
    supported_expense_types: str | None = Column("JSON")
    categories: str | None = Column("JSON")
    stats: str | None = Column("JSON")
    can_have_changelog_updates: bool | None = Column("BOOLEAN")
    features: str | None = Column("JSON")
    policies: str | None = Column("JSON")
    permissions: str | None = Column("JSON")
    transaction_reports: str | None = Column("JSON")
    description: str | None = Column("VARCHAR")
    website: str | None = Column("VARCHAR")
    background_image_url: str | None = Column("VARCHAR")
    tags: str | None = Column("JSON")
    github_handle: str | None = Column("VARCHAR")
    repository_url: str | None = Column("VARCHAR")
    location: str | None = Column("JSON")
    parent_account: str | None = Column("JSON")
    twitter_handle: str | None = Column("VARCHAR")
    transferwise: str | None = Column("JSON")
    member_invitations: str | None = Column("JSON")
    legal_documents: str | None = Column("JSON")
    emails: str | None = Column("JSON")
    payout_methods: str | None = Column("JSON")
    payment_methods: str | None = Column("JSON")
    payment_methods_with_pending_confirmation: str | None = Column("JSON")
    connected_accounts: str | None = Column("JSON")
    dlt_load_id: str = Column("VARCHAR", column_name="_dlt_load_id")
    dlt_id: str = Column("VARCHAR", column_name="_dlt_id")


seed = SeedConfig(
    catalog="bigquery",
    schema="open_collective",
    table="accounts",
    base=Accounts,
    rows=[
        Accounts(
            id="eeng0kzd-yvor4pzn-dgpbma83-7xlw95jl",
            legacy_id=9701,
            slug="big-nerd-ranch",
            type="INDIVIDUAL",
            name="Big Nerd Ranch",
            long_description=None,
            social_links="[]",
            currency="USD",
            expense_policy="",
            is_verified=False,
            is_incognito=False,
            image_url="https://images.opencollective.com/big-nerd-ranch/avatar.png",
            created_at=datetime(2025, 8, 19, 19, 56, 13, 52000),
            updated_at=datetime(2025, 8, 19, 17, 17, 8, 16000),
            is_archived=False,
            is_frozen=False,
            is_suspended=False,
            is_active=False,
            is_host=False,
            is_admin=False,
            settings="{}",
            supported_expense_types='["INVOICE", "RECEIPT"]',
            categories="[]",
            stats='{"activeRecurringContributions":{"CollectiveId":9701,"monthly":0,"monthlyCount":0,"yearly":0,"yearlyCount":0},"balance":{"currency":"USD","value":0,"valueInCents":0},"totalAmountReceived":{"currency":"USD","value":0,"valueInCents":0}}',
            can_have_changelog_updates=False,
            features='{"ABOUT":"AVAILABLE","ACCOUNT_MANAGEMENT":"ACTIVE","ORDER":"ACTIVE"}',
            policies='{"COLLECTIVE_MINIMUM_ADMINS":{"applies":"NEW_COLLECTIVES","freeze":false,"numberOfAdmins":0}}',
            permissions='{"addFunds":{"allowed":false,"reason":null,"reasonDetails":null}}',
            transaction_reports='{"dateFrom":null,"dateTo":null,"nodes":[],"timeUnit":"MONTH"}',
            description=None,
            website=None,
            background_image_url=None,
            tags="null",
            github_handle=None,
            repository_url=None,
            location="null",
            parent_account="null",
            twitter_handle=None,
            transferwise="null",
            member_invitations="null",
            legal_documents="null",
            emails="null",
            payout_methods="null",
            payment_methods="null",
            payment_methods_with_pending_confirmation="null",
            connected_accounts="null",
            dlt_load_id="1755719508.455616",
            dlt_id="geEdKazutWlwVQ",
        ),
        Accounts(
            id="eeng0kzd-yvor4pzv-lrqbma83-7xlw95jl",
            legacy_id=4401,
            slug="bignerdranch",
            type="ORGANIZATION",
            name="Big Nerd Ranch",
            long_description="<p>Big Nerd Ranch specializes in developing and designing innovative applications for clients around the world. We work with companies of all types, from startups to nonprofits to large enterprise clients.</p>",
            social_links='[{"createdAt":"2023-01-06T12:16:03.418Z","type":"WEBSITE","updatedAt":"2023-01-06T12:16:03.418Z","url":"https://bignerdranch.com"}]',
            currency="USD",
            expense_policy="",
            is_verified=False,
            is_incognito=False,
            image_url="https://images.opencollective.com/bignerdranch/c75de62/logo.png",
            created_at=datetime(2025, 8, 20, 19, 56, 13, 52000),
            updated_at=datetime(2025, 8, 20, 19, 56, 13, 52000),
            is_archived=False,
            is_frozen=False,
            is_suspended=False,
            is_active=False,
            is_host=False,
            is_admin=False,
            settings="{}",
            supported_expense_types='["INVOICE", "RECEIPT"]',
            categories="[]",
            stats='{"activeRecurringContributions":{"CollectiveId":4401,"monthly":0,"monthlyCount":0,"yearly":0,"yearlyCount":0},"balance":{"currency":"USD","value":-2775.73,"valueInCents":-277573}}',
            can_have_changelog_updates=False,
            features='{"ABOUT":"ACTIVE","ACCOUNT_MANAGEMENT":"ACTIVE","RECEIVE_EXPENSES":"AVAILABLE","TEAM":"ACTIVE"}',
            policies='{"COLLECTIVE_MINIMUM_ADMINS":{"applies":"NEW_COLLECTIVES","freeze":false,"numberOfAdmins":0}}',
            permissions='{"addFunds":{"allowed":false,"reason":null,"reasonDetails":null}}',
            transaction_reports='{"dateFrom":null,"dateTo":null,"nodes":[{"date":"2025-08-01T00:00:00.000Z"},{"date":"2025-07-01T00:00:00.000Z"}],"timeUnit":"MONTH"}',
            description="App Development & Training Since 2001",
            website="https://bignerdranch.com",
            background_image_url=None,
            tags='["user"]',
            github_handle=None,
            repository_url=None,
            location='{"address":null,"country":null,"id":null,"lat":null,"long":null,"name":null,"structured":null}',
            parent_account="null",
            twitter_handle=None,
            transferwise="null",
            member_invitations="null",
            legal_documents="null",
            emails="null",
            payout_methods="null",
            payment_methods="null",
            payment_methods_with_pending_confirmation="null",
            connected_accounts="null",
            dlt_load_id="1755719508.455616",
            dlt_id="oxYwVPRWlBNI0g",
        ),
        Accounts(
            id="3z8arxve-ymko60y4-l9wqgl5n-bj9w704d",
            legacy_id=615555,
            slug="chris-b",
            type="INDIVIDUAL",
            name="Chris B",
            long_description=None,
            social_links="[]",
            currency="USD",
            expense_policy="",
            is_verified=False,
            is_incognito=False,
            image_url="https://images.opencollective.com/chris-b/avatar.png",
            created_at=datetime(2025, 8, 21, 23, 54, 15, 454000),
            updated_at=datetime(2025, 8, 21, 13, 55, 54, 981000),
            is_archived=False,
            is_frozen=False,
            is_suspended=False,
            is_active=False,
            is_host=False,
            is_admin=False,
            settings='{"earlyAccess":{"CROWDFUNDING_REDESIGN":true,"HOST_REPORTS":true}}',
            supported_expense_types='["INVOICE", "RECEIPT"]',
            categories="[]",
            stats='{"activeRecurringContributions":{"CollectiveId":615555,"monthly":0,"monthlyCount":0,"yearly":0,"yearlyCount":0},"balance":{"currency":"USD","value":-234.65,"valueInCents":-23465}}',
            can_have_changelog_updates=False,
            features='{"ABOUT":"AVAILABLE","ACCOUNT_MANAGEMENT":"ACTIVE","RECURRING_CONTRIBUTIONS":"ACTIVE","TRANSACTIONS":"ACTIVE"}',
            policies='{"COLLECTIVE_MINIMUM_ADMINS":{"applies":"NEW_COLLECTIVES","freeze":false,"numberOfAdmins":0}}',
            permissions='{"addFunds":{"allowed":false,"reason":null,"reasonDetails":null}}',
            transaction_reports='{"dateFrom":null,"dateTo":null,"nodes":[{"date":"2025-08-01T00:00:00.000Z"},{"date":"2025-07-01T00:00:00.000Z"}],"timeUnit":"MONTH"}',
            description=None,
            website=None,
            background_image_url=None,
            tags="null",
            github_handle=None,
            repository_url=None,
            location="null",
            parent_account="null",
            twitter_handle=None,
            transferwise="null",
            member_invitations="null",
            legal_documents="null",
            emails="null",
            payout_methods="null",
            payment_methods="null",
            payment_methods_with_pending_confirmation="null",
            connected_accounts="null",
            dlt_load_id="1755719508.455616",
            dlt_id="cEwdTpUcj332Aw",
        ),
    ],
)
