model(
  name oso.artifacts_by_user_v1, 
  kind full, 
  tags('export'), 
  enabled false,
  audits (
    not_null(columns := (artifact_id, user_id))
  ),
  description 'The `artifacts_by_user_v1` table represents the relationship between users and the artifacts owned by the users. An artifact is an open source work contribution that belongs to a user, for instance a GitHub user account, or an EOA blockchain address. This table is primarily used to lookup artifacts owned by users.',
  column_descriptions (
    artifact_id = 'The unique identifier for the artifact.',
    artifact_source_id = 'The native identifier for the artifact from the source, such as a GitHub repository ID or NPM package ID.',
    artifact_source = 'The original source of the artifact, such as "GITHUB", "NPM", or "DEFILLAMA".',
    artifact_namespace = 'The grouping or namespace of the artifact, such as the GitHub organization or NPM scope. It will will be empty if the artifact source does not have its own namespacing conventions',
    artifact_name = 'The name of the artifact, such as the GitHub repository name, NPM package name, or blockchain address.',
    user_id = 'The unique identifier for the user that owns the artifact, as generated by OSO.',
    user_source_id = 'The unique identifier for the user the comes from source.',
    user_source = 'The source of the user, such as "ENS" or "FARCASTER".',
    user_namespace = 'The grouping or namespace of the user.',
    user_name = 'The unique name of the user.'
  )
)
;

select
    artifact_id,
    artifact_source_id,
    artifact_source,
    artifact_namespace,
    artifact_name,
    user_id,
    user_source_id,
    user_source,
    user_type,
    user_namespace,
    user_name
from oso.int_artifacts_by_user
