MODEL (
  name oso.projects_v1,
  kind FULL,
  tags (
    'export',
    'entity_category=project'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  description 'This table represents individual projects in the OSO data warehouse. Projects are the primary entities that metrics are calculated for. This data is mostly used to lookup metadata about a project once you have its project_id. The project_id is generated by hashing the project_source, project_namespace, and project_name fields. Common business questions include: What is the project_id associated with Uniswap? How many projects are in OP Atlas? Which projects might be duplicates?',
  column_descriptions (
    project_id = 'The unique identifier for the project, as generated by OSO.',
    project_source = 'The source of the project, such as "OSS_DIRECTORY", or "OP_ATLAS".',
    project_namespace = 'The namespace of the project within the source, which may include organization information.',
    project_name = 'the project slug or other name given to the project (unique to the registry but not globally unique)',
    display_name = 'The display name of the project, which may be a more human-readable name than the project_name.',
    description = 'A short description of the project.'
  )
);

SELECT
  projects.project_id,
  projects.project_source,
  projects.project_namespace,
  projects.project_name,
  projects.display_name,
  projects.description
FROM oso.int_projects AS projects
