MODEL (
  name oso.users_v1,
  kind FULL,
  tags (
    'export'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  enabled false,
  description 'This model contains user profiles, including their unique identifiers, source information, display names, profile pictures, bios, and URLs. It is used to capture user identity across the OSO platform.',
  column_descriptions (
    user_id = 'The unique identifier for the user, as generated by OSO.',
    user_source_id = 'The unique identifier for the user from the source, such as a GitHub user ID or ENS address.',
    user_source = 'The source of the user, such as "GITHUB", "ENS", or "FARCASTER".',
    display_name = 'The display name of the user, which may be their real name or a username.',
    profile_picture_url = 'The URL to the user profile picture.',
    bio = 'A short biography or description of the user.',
    url = 'A URL to the user website.'
  )
);

SELECT
  users.user_id,
  users.user_source_id,
  users.user_source,
  users.display_name,
  users.profile_picture_url,
  users.bio,
  users.url
FROM oso.int_users AS users