MODEL (
  name oso.key_metrics_by_project_v0,
  kind FULL,
  partitioned_by year(sample_date),
  tags (
    'export',
    'model_type=full',
    'model_category=metrics',
    'model_stage=mart',
    'entity_category=project'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  description 'Each row represents a specific metric value for an open source project at a recent date, capturing the metric type, the associated project, the measured amount, and its unit. This data can be used to analyze trends and performance indicators across different projects for business insights such as growth, engagement, or risk. Business questions that can be answered include: Which projects currently have the most activity? How many contributors are currently involved in the project?',
  column_descriptions (
    metric_id = 'The unique identifier for the metric, generated by OSO.',
    project_id = 'The unique identifier for the project, as generated by OSO.',
    sample_date = 'The date when the metric was sampled, truncated to the day. This is typically a recent date.',
    amount = 'The value of the metric for the project on the sample date.',
    unit = 'The unit of measurement for the metric, if applicable.'
  )
);

WITH key_metrics_by_project_v0_no_casting AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_project_id AS project_id,
    metrics_sample_date AS sample_date,
    amount,
    metric,
    NULL AS unit
  FROM oso.key_metrics_to_project
)
SELECT
  metric_id::TEXT,
  project_id::TEXT,
  sample_date::DATE,
  amount::DOUBLE,
  unit::TEXT
FROM key_metrics_by_project_v0_no_casting
