MODEL (
  name oso.metrics_v0,
  kind FULL,
  dialect trino,
  tags (
    'export',
    'model_type=full',
    'model_category=metrics',
    'model_stage=mart'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  description 'Each row represents metadata about a unique metric. This data can be used to analyze trends and performance indicators across various open source projects, supporting business decisions around developer engagement, funding, and project health. This table is necessary for doing keyword searches to discover relevant metrics ids, and joining on the other metrics tables (eg, key_metrics_by_project_v0 and timeseries_metrics_by_project_v0). Business questions that can be answered include: Which daily metrics are available for "BASE"? What are the available metric ids for GITHUB_stars? Which metrics are relevant to contract artifacts on "OPTIMISM"?',
  column_descriptions (
    metric_id = 'The unique identifier for the metric, generated by OSO.',
    metric_source = 'The source of the metric, typically "OSO".',
    metric_namespace = 'The namespace grouping of the metric.',
    metric_name = 'The name of the metric, such as "S7_M1_devtooling_reward".',
    display_name = 'A human-readable name for the metric, such as "S7 M1 Dev Tooling Reward".',
    description = 'A description of the metric, providing context and details about what it measures.',
    rendered_sql = 'The SQL query used to compute the metric, if applicable.',
    sql_source_path = 'The path to the SQL file that defines the metric.'
  )
);

/* TODO: We currenly hardcode a set of key metrics coming from OP Atlas */
WITH op_atlas_metric_names AS (
  SELECT DISTINCT
    metric
  FROM oso.int_superchain_s7_m1_rewards
),
unioned_metric_names AS (
  SELECT
    *
  FROM oso.int_metric_names_from_artifact
  UNION ALL
  SELECT
    *
  FROM oso.int_metric_names_from_project
  UNION ALL
  SELECT
    *
  FROM oso.int_metric_names_from_collection
  UNION ALL
  SELECT
    *
  FROM oso.int_key_metric_names_from_artifact
  UNION ALL
  SELECT
    *
  FROM oso.int_key_metric_names_from_project
  UNION ALL
  SELECT
    *
  FROM oso.int_key_metric_names_from_collection
  UNION ALL
  SELECT
    *
  FROM op_atlas_metric_names
), 
op_atlas_metrics_metadata AS (
  SELECT
    'S7_M1_devtooling_reward' AS metric,
    'S7 M1 Dev Tooling Reward' AS display_name,
    'Rewards for Retro Funding S7 - Measurement Period 1 (Feb 2025) - Dev Tooling' AS description,
    'warehouse/oso_sqlmesh/models/intermediate/superchain/s7/rewards/int_superchain_s7_m1_rewards.sql' AS sql_source_path,
    ARRAY['SELECT * FROM oso.int_superchain_s7_m1_rewards WHERE metric = ''S7_M1_devtooling_reward'''] AS rendered_sql
  UNION ALL
  SELECT
    'S7_M1_onchain_builder_reward' AS metric,
    'S7 M1 Onchain Builder Reward' AS display_name,
    'Rewards for Retro Funding S7 - Measurement Period 1 (Feb 2025) - Onchain Builder' AS description,
    'warehouse/oso_sqlmesh/models/intermediate/superchain/s7/rewards/int_superchain_s7_m1_rewards.sql' AS sql_source_path,
    ARRAY['SELECT * FROM oso.int_superchain_s7_m1_rewards WHERE metric = ''S7_M1_onchain_builder_reward'''] AS rendered_sql
),
all_timeseries_metric_names AS (
  SELECT DISTINCT
    metric
  FROM unioned_metric_names
), all_metrics_metadata AS (
  SELECT
    metric,
    display_name,
    description,
    sql_source_path,
    rendered_sql
  FROM oso.metrics_metadata
  UNION ALL
  SELECT
    metric,
    display_name,
    description,
    sql_source_path,
    rendered_sql
  FROM op_atlas_metrics_metadata
), metrics_v0_no_casting AS (
  SELECT
    @oso_id('OSO', 'oso', t.metric) AS metric_id,
    'OSO' AS metric_source,
    'oso' AS metric_namespace,
    t.metric AS metric_name,
    COALESCE(m.display_name, t.metric) AS display_name,
    COALESCE(m.description, 'TODO') AS description,
    COALESCE(m.rendered_sql, []) AS rendered_sql,
    COALESCE(m.sql_source_path, 'TODO') AS sql_source_path,
    'UNKNOWN' AS aggregation_function
  FROM all_timeseries_metric_names AS t
  LEFT JOIN all_metrics_metadata AS m
    ON t.metric LIKE '%' || m.metric || '%'
)
SELECT
  metric_id::VARCHAR,
  metric_source::VARCHAR,
  metric_namespace::VARCHAR,
  metric_name::VARCHAR,
  display_name::VARCHAR,
  description::VARCHAR,
  rendered_sql,
  sql_source_path::VARCHAR,
  aggregation_function::VARCHAR
FROM metrics_v0_no_casting
