MODEL (
  name oso.timeseries_metrics_by_collection_v0,
  kind FULL,
  partitioned_by year(sample_date),
  tags (
    'export',
    'model_type=full',
    'model_category=metrics',
    'model_stage=mart',
    'entity_category=collection'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  description 'Many-to-many table between metrics, collections, and dates. Each row represents the value of a specific metric for a given collection on a particular date, capturing how that metric changes over time. This is one of the most important models for OSO and should be used frequently in analysis. However, in order to use this table correctly, it is necessary to join on metrics_v0 and collections_v1 (or other collection-related tables). Business questions that can be answered include: Which collections have the most active developers? How many forks does this collection have? Which collections grew TVL the most over the last 3 months?',
  column_descriptions (
    metric_id = 'The unique identifier for the metric, generated by OSO.',
    collection_id = 'The unique identifier for the collection, as generated by OSO.',
    sample_date = 'The date when the metric was sampled, truncated to the day.',
    amount = 'The value of the metric for the collection on the sample date.',
    unit = 'The unit of measurement for the metric, if applicable.'
  )
);

WITH all_key_metrics_by_collection AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_collection_id AS collection_id,
    metrics_sample_date AS sample_date,
    amount,
    NULL AS unit
  FROM oso.key_metrics_to_collection
),
all_timeseries_metrics_by_collection AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_collection_id AS collection_id,
    metrics_sample_date AS sample_date,
    amount AS amount,
    NULL AS unit
  FROM oso.timeseries_metrics_to_collection
),
unioned_metrics_by_collection AS (
  SELECT * FROM all_key_metrics_by_collection
  UNION ALL
  SELECT * FROM all_timeseries_metrics_by_collection
)

SELECT
  metric_id::TEXT,
  collection_id::TEXT,
  sample_date::DATE,
  amount::DOUBLE,
  unit::TEXT
FROM unioned_metrics_by_collection
