MODEL (
  name oso.timeseries_metrics_by_project_v0,
  kind FULL,
  partitioned_by year(sample_date),
  dialect trino,
  tags (
    'export',
    'model_type=full',
    'model_category=metrics',
    'model_stage=mart',
    'entity_category=project'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  description 'Many-to-many table between metrics, projects, and dates. Each row represents the value of a specific metric for a given open source project on a particular date, capturing how that metric changes over time. This is one of the most important models for OSO and should be used frequently in analysis. However, in order to use this table correctly, it is necessary to join on metrics_v0 and projects_v1 (or other project-related tables). Business questions that can be answered include: Which projects have the most active developers? How many forks does this project have? Which projects grew TVL the most over the last 3 months?',
  column_descriptions (
    metric_id = 'The unique identifier for the metric, generated by OSO.',
    project_id = 'The unique identifier for the project, as generated by OSO.',
    sample_date = 'The date when the metric was sampled, truncated to the day.',
    amount = 'The value of the metric for the project on the sample date.',
    unit = 'The unit of measurement for the metric, if applicable.'
  )
);

WITH all_key_metrics_by_project AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_project_id AS project_id,
    metrics_sample_date AS sample_date,
    amount,
    NULL AS unit
  FROM oso.key_metrics_to_project
),
all_timeseries_metrics_by_project AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_project_id AS project_id,
    metrics_sample_date AS sample_date,
    amount AS amount,
    NULL AS unit
  FROM oso.timeseries_metrics_to_project
),
/* TODO: Remove this once we have a more permanent source for these metrics */
op_atlas_metrics_by_project AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    project_id,
    sample_date,
    amount,
    'OP' AS unit
  FROM oso.int_superchain_s7_m1_rewards
),
unioned_metrics_by_project AS (
  SELECT * FROM all_key_metrics_by_project
  UNION ALL
  SELECT * FROM all_timeseries_metrics_by_project
  UNION ALL
  SELECT * FROM op_atlas_metrics_by_project
)

SELECT
  metric_id::TEXT,
  project_id::TEXT,
  sample_date::DATE,
  amount::DOUBLE,
  unit::TEXT
FROM unioned_metrics_by_project
