MODEL (
  name oso.timeseries_metrics_by_artifact_v0,
  kind FULL,
  partitioned_by (year(sample_date), bucket(artifact_id, 256)),
  tags (
    'export',
    'model_type=full',
    'model_category=metrics',
    'model_stage=mart'
  ),
  audits (
    has_at_least_n_rows(threshold := 0)
  ),
  description 'Many-to-many table between metrics, artifacts, and dates. Each row represents the value of a specific metric for a given artifact on a particular date, capturing how that metric changes over time. This is one of the most important models for OSO and should be used frequently in analysis. However, in order to use this table correctly, it is necessary to join on metrics_v0 and artifacts_v1 (or other artifact-related tables). Business questions that can be answered include: Which artifacts have the most active developers? How many forks does this artifact have?',
  column_descriptions (
    metric_id = 'The unique identifier for the metric, generated by OSO.',
    artifact_id = 'The unique identifier for the artifact, as generated by OSO.',
    sample_date = 'The date when the metric was sampled, truncated to the day.',
    amount = 'The value of the metric for the artifact on the sample date.',
    unit = 'The unit of measurement for the metric, if applicable.'
  ),
  physical_properties (
    parquet_bloom_filter_columns = ['artifact_id'],
    sorted_by = ['artifact_id']
  )
);

WITH all_key_metrics_by_artifact AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_artifact_id AS artifact_id,
    metrics_sample_date AS sample_date,
    amount,
    NULL AS unit
  FROM oso.key_metrics_to_artifact
),
all_timeseries_metrics_by_artifact AS (
  SELECT
    @oso_id('OSO', 'oso', metric) AS metric_id,
    to_artifact_id AS artifact_id,
    metrics_sample_date AS sample_date,
    amount AS amount,
    NULL AS unit
  FROM oso.timeseries_metrics_to_artifact
),
unioned_metrics_by_artifact AS (
  SELECT * FROM all_key_metrics_by_artifact
  UNION ALL
  SELECT * FROM all_timeseries_metrics_by_artifact
)

SELECT
  metric_id::TEXT,
  artifact_id::TEXT,
  sample_date::DATE,
  amount::DOUBLE,
  unit::TEXT
FROM unioned_metrics_by_artifact