apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/open-policy-agent
  - ./opa-pdb.yaml
namespace: production-open-policy-agent
patches:
  - path: opa-deployment.yaml
    target:
      kind: Deployment