apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      serviceAccountName: production-opa
      containers:
        - name: opa
          image: openpolicyagent/opa:1.4.2
          ports:
            - name: http
              containerPort: 8181
