MODEL (
  name oso.stg_open_collective__accounts,
  dialect trino,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column created_at,
    batch_size 365,
    batch_concurrency 2,
    lookback 31,
    forward_only true,
  ),
  partitioned_by (DAY("created_at")),
  start '2015-01-01',
  cron '@daily',
  audits (
    has_at_least_n_rows(threshold := 0),
  ),
  ignored_rules (
    "incrementalmustdefinenogapsaudit",
  ),
  tags (
    "incremental"
  )
);

SELECT
  id,
  legacy_id,
  slug,
  type,
  name,
  long_description,
  JSON_FORMAT(social_links) AS social_links,
  currency,
  expense_policy,
  is_verified,
  is_incognito,
  image_url,
  created_at,
  updated_at,
  is_archived,
  is_frozen,
  is_suspended,
  is_active,
  is_host,
  is_admin,
  JSON_FORMAT(settings) AS settings,
  JSON_FORMAT(supported_expense_types) AS supported_expense_types,
  JSON_FORMAT(categories) AS categories,
  JSON_FORMAT(stats) AS stats,
  can_have_changelog_updates,
  JSON_FORMAT(features) AS features,
  JSON_FORMAT(policies) AS policies,
  JSON_FORMAT(permissions) AS permissions,
  JSON_FORMAT(transaction_reports) AS transaction_reports,
  _dlt_load_id,
  _dlt_id,
  description,
  website,
  background_image_url,
  JSON_FORMAT(tags) AS tags,
  github_handle,
  repository_url,
  JSON_FORMAT(location) AS location,
  JSON_FORMAT(parent_account) AS parent_account,
  twitter_handle,
  JSON_FORMAT(transferwise) AS transferwise,
  JSON_FORMAT(member_invitations) AS member_invitations,
  JSON_FORMAT(legal_documents) AS legal_documents,
  JSON_FORMAT(emails) AS emails,
  JSON_FORMAT(payout_methods) AS payout_methods,
  JSON_FORMAT(payment_methods) AS payment_methods,
  JSON_FORMAT(payment_methods_with_pending_confirmation) AS payment_methods_with_pending_confirmation,
  JSON_FORMAT(connected_accounts) AS connected_accounts
FROM @oso_source('bigquery.open_collective.accounts')
