MODEL (
  name oso.stg_open_collective__accounts,
  dialect trino,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column created_at,
    batch_size 365,
    batch_concurrency 2,
    lookback 31,
    forward_only true,
  ),
  partitioned_by (DAY("created_at")),
  start '2015-01-01',
  cron '@daily',
  audits (
    has_at_least_n_rows(threshold := 0),
  ),
  ignored_rules (
    "incrementalmustdefinenogapsaudit",
  ),
  tags (
    "incremental"
  )
);

SELECT
  id,
  legacy_id,
  slug,
  type,
  name,
  long_description,
  social_links,
  currency,
  expense_policy,
  is_verified,
  is_incognito,
  image_url,
  created_at,
  updated_at,
  is_archived,
  is_frozen,
  is_suspended,
  is_active,
  is_host,
  is_admin,
  settings,
  supported_expense_types,
  categories,
  stats,
  can_have_changelog_updates,
  features,
  policies,
  permissions,
  transaction_reports,
  _dlt_load_id,
  _dlt_id,
  description,
  website,
  background_image_url,
  tags,
  github_handle,
  repository_url,
  location,
  parent_account,
  twitter_handle,
  transferwise,
  member_invitations,
  legal_documents,
  emails,
  payout_methods,
  payment_methods,
  payment_methods_with_pending_confirmation,
  connected_accounts
FROM @oso_source('bigquery.open_collective.accounts')
