apiVersion: batch/v1
kind: CronJob
metadata:
  name: pynessie-gc-job
spec:
  schedule: "0 0 * * 2"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pynessie-gc
              image: ghcr.io/opensource-observer/oso:latest
              command: ["uv", "run", "pynessie-gc"]
              env:
                - name: BUKCET_NAME
                  value: oso-iceberg-usc1
                - name: TRINO_HOST
                  value: production-trino-trino.production-trino.svc.cluster.local
                - name: TRINO_PORT
                  value: "8080"
                - name: TRINO_SCHEMA
                  value: sqlmesh__oso
                - name: CONCURRENCY_LIMIT
                  value: "3"
              resources:
                requests:
                  cpu: 1
                  memory: 1Gi
                limits:
                  memory: 2Gi
          restartPolicy: Never
          serviceAccountName: production-nessie
