---
apiVersion: v1
kind: Secret
metadata:
  name: nessie-postgres
type: Opaque
data:
  username: Z2NwOnNlY3JldG1hbmFnZXI6cHJvZHVjdGlvbi1uZXNzaWUtZGItdXNlcg==
  password: Z2NwOnNlY3JldG1hbmFnZXI6cHJvZHVjdGlvbi1uZXNzaWUtZGItcGFzc3dvcmQ=
