---
apiVersion: v1
kind: Namespace
metadata:
  name: dask-operator
  labels:
    toolkit.fluxcd.io/tenant: ops
    opensource.observer/cert-inject: "enabled"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dask
  namespace: dask-operator
spec:
  interval: 24h
  url: https://helm.dask.org/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dask-operator
  namespace: dask-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: dask-kubernetes-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: dask
        namespace: dask-operator
      interval: 1h