apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-sqlmesh-cloudsql-proxy
spec:
  values:
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: prod-sqlmesh-sql-proxy
    cloudsql:
      instances:
        - instance: sqlmesh-psql
          region: us-central1
          project: opensource-observer
          port: 5432