"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DataModelRunRequest(google.protobuf.message.Message):
    """*
    A request to run a user defined model
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    DATASET_ID_FIELD_NUMBER: builtins.int
    MODEL_RELEASE_IDS_FIELD_NUMBER: builtins.int
    run_id: builtins.bytes
    dataset_id: builtins.str
    """The dataset on which the models are to be run"""
    @property
    def model_release_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """IDs of the models to run on the dataset. Should not be empty."""

    def __init__(
        self,
        *,
        run_id: builtins.bytes = ...,
        dataset_id: builtins.str = ...,
        model_release_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dataset_id", b"dataset_id", "model_release_ids", b"model_release_ids", "run_id", b"run_id"]) -> None: ...

Global___DataModelRunRequest: typing_extensions.TypeAlias = DataModelRunRequest
