"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DataIngestionRunRequest(google.protobuf.message.Message):
    """*
    A request to materiaize a data ingestion dataset
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    DATASET_ID_FIELD_NUMBER: builtins.int
    run_id: builtins.bytes
    dataset_id: builtins.str
    def __init__(
        self,
        *,
        run_id: builtins.bytes = ...,
        dataset_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dataset_id", b"dataset_id", "run_id", b"run_id"]) -> None: ...

Global___DataIngestionRunRequest: typing_extensions.TypeAlias = DataIngestionRunRequest
