"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryRunRequest(google.protobuf.message.Message):
    """*
    A request to run a query on the trino cluster. The results will be stored
    and can be retrieved later using the request_id.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    JWT_FIELD_NUMBER: builtins.int
    METADATA_JSON_FIELD_NUMBER: builtins.int
    run_id: builtins.bytes
    query: builtins.str
    """The query should be sent as is to the workers. Any rewriting will be
    handled at the worker
    """
    jwt: builtins.str
    """The JWT of the user making the request. This is used to authenticate the 
    request and authorize access to the data on trino.
    """
    metadata_json: builtins.str
    """Metadata passed on to the workers for query rewriting inference. This is
    expected to be a JSON string.
    """
    def __init__(
        self,
        *,
        run_id: builtins.bytes = ...,
        query: builtins.str = ...,
        jwt: builtins.str = ...,
        metadata_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["jwt", b"jwt", "metadata_json", b"metadata_json", "query", b"query", "run_id", b"run_id"]) -> None: ...

Global___QueryRunRequest: typing_extensions.TypeAlias = QueryRunRequest
