# This service exposes the notification controller to the cluster so that we can
# connect to the cluster from a github action and send a webhook to the
# notification controller to trigger image updates
#
# Specifically this is _not_ a service that is exposed to the outside world
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9292
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: oso-image
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: oso
      namespace: flux-system