apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec: 
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system 
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      messageTemplate: |
        Automated production image update #production-deploy

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}        
      author:
        email: 152447233+karibabot@users.noreply.github.com
        name: karibabot
  update:
    path: ./ops/
    strategy: Setters