# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Any, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .create_data_connection_datasets import CreateDataConnectionDatasets
from .create_materialization import CreateMaterialization
from .enums import RunStatus, StepStatus
from .finish_run import FinishRun
from .finish_step import FinishStep
from .get_data_connection import GetDataConnection
from .get_data_ingestion_config import GetDataIngestionConfig
from .get_data_models import GetDataModels
from .get_notebook import GetNotebook
from .get_run import GetRun
from .get_static_models import GetStaticModels
from .input_types import (
    DataConnectionSchemaInput,
    DataModelColumnInput,
    UpdateMetadataInput,
)
from .resolve_tables import ResolveTables
from .save_published_notebook_html import SavePublishedNotebookHtml
from .start_run import StartRun
from .start_step import StartStep
from .update_run_metadata import UpdateRunMetadata


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def start_run(self, run_id: str, **kwargs: Any) -> StartRun:
        query = gql(
            """
            mutation StartRun($runId: ID!) {
              startRun(input: {runId: $runId}) {
                success
              }
            }
            """
        )
        variables: Dict[str, object] = {"runId": run_id}
        response = await self.execute(
            query=query, operation_name="StartRun", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return StartRun.model_validate(data)

    async def update_run_metadata(
        self, run_id: str, metadata: UpdateMetadataInput, **kwargs: Any
    ) -> UpdateRunMetadata:
        query = gql(
            """
            mutation UpdateRunMetadata($runId: ID!, $metadata: UpdateMetadataInput!) {
              updateRunMetadata(input: {runId: $runId, metadata: $metadata}) {
                success
                message
                run {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"runId": run_id, "metadata": metadata}
        response = await self.execute(
            query=query,
            operation_name="UpdateRunMetadata",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return UpdateRunMetadata.model_validate(data)

    async def finish_run(
        self,
        run_id: str,
        status: RunStatus,
        status_code: int,
        logs_url: str,
        metadata: Union[Optional[UpdateMetadataInput], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> FinishRun:
        query = gql(
            """
            mutation FinishRun($runId: ID!, $status: RunStatus!, $statusCode: Int!, $logsUrl: String!, $metadata: UpdateMetadataInput) {
              finishRun(
                input: {runId: $runId, status: $status, statusCode: $statusCode, logsUrl: $logsUrl, metadata: $metadata}
              ) {
                success
                message
                run {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "runId": run_id,
            "status": status,
            "statusCode": status_code,
            "logsUrl": logs_url,
            "metadata": metadata,
        }
        response = await self.execute(
            query=query, operation_name="FinishRun", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FinishRun.model_validate(data)

    async def start_step(
        self, run_id: str, name: str, display_name: str, **kwargs: Any
    ) -> StartStep:
        query = gql(
            """
            mutation StartStep($runId: ID!, $name: String!, $displayName: String!) {
              startStep(input: {runId: $runId, name: $name, displayName: $displayName}) {
                success
                message
                step {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "runId": run_id,
            "name": name,
            "displayName": display_name,
        }
        response = await self.execute(
            query=query, operation_name="StartStep", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return StartStep.model_validate(data)

    async def finish_step(
        self, step_id: str, status: StepStatus, logs_url: str, **kwargs: Any
    ) -> FinishStep:
        query = gql(
            """
            mutation FinishStep($stepId: ID!, $status: StepStatus!, $logsUrl: String!) {
              finishStep(input: {stepId: $stepId, status: $status, logsUrl: $logsUrl}) {
                success
                message
                step {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "stepId": step_id,
            "status": status,
            "logsUrl": logs_url,
        }
        response = await self.execute(
            query=query, operation_name="FinishStep", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FinishStep.model_validate(data)

    async def create_materialization(
        self,
        step_id: str,
        table_id: str,
        warehouse_fqn: str,
        schema: List[DataModelColumnInput],
        **kwargs: Any,
    ) -> CreateMaterialization:
        query = gql(
            """
            mutation CreateMaterialization($stepId: ID!, $tableId: ID!, $warehouseFqn: String!, $schema: [DataModelColumnInput!]!) {
              createMaterialization(
                input: {stepId: $stepId, tableId: $tableId, warehouseFqn: $warehouseFqn, schema: $schema}
              ) {
                success
                materialization {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "stepId": step_id,
            "tableId": table_id,
            "warehouseFqn": warehouse_fqn,
            "schema": schema,
        }
        response = await self.execute(
            query=query,
            operation_name="CreateMaterialization",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CreateMaterialization.model_validate(data)

    async def save_published_notebook_html(
        self, notebook_id: str, html_content: str, **kwargs: Any
    ) -> SavePublishedNotebookHtml:
        query = gql(
            """
            mutation SavePublishedNotebookHtml($notebookId: ID!, $htmlContent: String!) {
              savePublishedNotebookHtml(
                input: {notebookId: $notebookId, htmlContent: $htmlContent}
              ) {
                success
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "notebookId": notebook_id,
            "htmlContent": html_content,
        }
        response = await self.execute(
            query=query,
            operation_name="SavePublishedNotebookHtml",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return SavePublishedNotebookHtml.model_validate(data)

    async def get_run(self, run_id: str, **kwargs: Any) -> GetRun:
        query = gql(
            """
            query GetRun($runId: ID!) {
              runs(where: {id: {eq: $runId}}, single: true) {
                edges {
                  node {
                    ...RunCommon
                  }
                }
              }
            }

            fragment DatasetCommon on Dataset {
              id
              name
              displayName
              description
              organization {
                ...OrganizationCommon
              }
            }

            fragment OrganizationCommon on Organization {
              id
              name
            }

            fragment RunCommon on Run {
              id
              metadata
              triggerType
              organization {
                ...OrganizationCommon
              }
              dataset {
                ...DatasetCommon
              }
              requestedBy {
                ...UserCommon
              }
            }

            fragment UserCommon on User {
              id
              email
            }
            """
        )
        variables: Dict[str, object] = {"runId": run_id}
        response = await self.execute(
            query=query, operation_name="GetRun", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetRun.model_validate(data)

    async def get_data_models(self, dataset_id: str, **kwargs: Any) -> GetDataModels:
        query = gql(
            """
            query GetDataModels($datasetId: ID!) {
              datasets(where: {id: {eq: $datasetId}}) {
                edges {
                  node {
                    ...DatasetCommon
                    typeDefinition {
                      __typename
                      ... on DataModelDefinition {
                        dataModels(where: {is_enabled: {eq: true}}) {
                          ...DataModels
                        }
                      }
                    }
                  }
                }
              }
            }

            fragment DataModels on DataModelConnection {
              edges {
                node {
                  ...LatestDataModel
                }
              }
            }

            fragment DatasetCommon on Dataset {
              id
              name
              displayName
              description
              organization {
                ...OrganizationCommon
              }
            }

            fragment LatestDataModel on DataModel {
              id
              orgId
              isEnabled
              createdAt
              latestRelease {
                id
                revision {
                  name
                  description
                  code
                  dependsOn {
                    alias
                    tableId
                  }
                  hash
                  kind
                  kindOptions {
                    timeColumn
                    timeColumnFormat
                    batchSize
                    lookback
                    uniqueKeyColumns
                    whenMatchedSql
                    mergeFilter
                    validFromName
                    validToName
                    invalidateHardDeletes
                    updatedAtColumn
                    updatedAtAsValidFrom
                    scdColumns
                    executionTimeAsValidFrom
                  }
                  partitionedBy
                  schema {
                    name
                    type
                    description
                  }
                  start
                  end
                  clusteredBy
                  language
                }
              }
            }

            fragment OrganizationCommon on Organization {
              id
              name
            }
            """
        )
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = await self.execute(
            query=query, operation_name="GetDataModels", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetDataModels.model_validate(data)

    async def get_data_ingestion_config(
        self, dataset_id: str, **kwargs: Any
    ) -> GetDataIngestionConfig:
        query = gql(
            """
            query GetDataIngestionConfig($datasetId: ID!) {
              datasets(where: {id: {eq: $datasetId}}, single: true) {
                edges {
                  node {
                    ...DatasetCommon
                    typeDefinition {
                      __typename
                      ... on DataIngestionDefinition {
                        dataIngestion {
                          id
                          datasetId
                          factoryType
                          config
                        }
                      }
                    }
                  }
                }
              }
            }

            fragment DatasetCommon on Dataset {
              id
              name
              displayName
              description
              organization {
                ...OrganizationCommon
              }
            }

            fragment OrganizationCommon on Organization {
              id
              name
            }
            """
        )
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = await self.execute(
            query=query,
            operation_name="GetDataIngestionConfig",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetDataIngestionConfig.model_validate(data)

    async def get_static_models(
        self, dataset_id: str, **kwargs: Any
    ) -> GetStaticModels:
        query = gql(
            """
            query GetStaticModels($datasetId: ID!) {
              datasets(where: {id: {eq: $datasetId}}) {
                edges {
                  node {
                    ...DatasetCommon
                    typeDefinition {
                      __typename
                      ... on StaticModelDefinition {
                        staticModels {
                          edges {
                            node {
                              id
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }

            fragment DatasetCommon on Dataset {
              id
              name
              displayName
              description
              organization {
                ...OrganizationCommon
              }
            }

            fragment OrganizationCommon on Organization {
              id
              name
            }
            """
        )
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = await self.execute(
            query=query, operation_name="GetStaticModels", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetStaticModels.model_validate(data)

    async def resolve_tables(
        self,
        references: List[str],
        metadata: Union[Optional[Any], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> ResolveTables:
        query = gql(
            """
            query ResolveTables($references: [String!]!, $metadata: JSON) {
              system {
                resolveTables(references: $references, metadata: $metadata) {
                  reference
                  fqn
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"references": references, "metadata": metadata}
        response = await self.execute(
            query=query, operation_name="ResolveTables", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ResolveTables.model_validate(data)

    async def get_notebook(self, notebook_id: str, **kwargs: Any) -> GetNotebook:
        query = gql(
            """
            query GetNotebook($notebookId: ID!) {
              notebooks(where: {id: {eq: $notebookId}}, single: true) {
                edges {
                  node {
                    id
                    name
                    data
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"notebookId": notebook_id}
        response = await self.execute(
            query=query, operation_name="GetNotebook", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetNotebook.model_validate(data)

    async def get_data_connection(
        self, connection_id: str, **kwargs: Any
    ) -> GetDataConnection:
        query = gql(
            """
            query GetDataConnection($connectionId: ID!) {
              dataConnections(where: {id: {eq: $connectionId}}, single: true) {
                edges {
                  node {
                    id
                    orgId
                    name
                    type
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"connectionId": connection_id}
        response = await self.execute(
            query=query,
            operation_name="GetDataConnection",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetDataConnection.model_validate(data)

    async def create_data_connection_datasets(
        self,
        run_id: str,
        org_id: str,
        data_connection_id: str,
        schemas: List[DataConnectionSchemaInput],
        **kwargs: Any,
    ) -> CreateDataConnectionDatasets:
        query = gql(
            """
            mutation CreateDataConnectionDatasets($runId: ID!, $orgId: ID!, $dataConnectionId: ID!, $schemas: [DataConnectionSchemaInput!]!) {
              createDataConnectionDatasets(
                input: {runId: $runId, orgId: $orgId, dataConnectionId: $dataConnectionId, schemas: $schemas}
              ) {
                success
                message
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "runId": run_id,
            "orgId": org_id,
            "dataConnectionId": data_connection_id,
            "schemas": schemas,
        }
        response = await self.execute(
            query=query,
            operation_name="CreateDataConnectionDatasets",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CreateDataConnectionDatasets.model_validate(data)
