# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from pydantic import Field

from .base_model import BaseModel


class CreateMaterialization(BaseModel):
    create_materialization: "CreateMaterializationCreateMaterialization" = Field(
        alias="createMaterialization"
    )


class CreateMaterializationCreateMaterialization(BaseModel):
    success: bool
    materialization: "CreateMaterializationCreateMaterializationMaterialization"


class CreateMaterializationCreateMaterializationMaterialization(BaseModel):
    id: str


CreateMaterialization.model_rebuild()
CreateMaterializationCreateMaterialization.model_rebuild()
