# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateDataConnectionAlias(BaseModel):
    create_data_connection_alias: "CreateDataConnectionAliasCreateDataConnectionAlias" = Field(
        alias="createDataConnectionAlias"
    )


class CreateDataConnectionAliasCreateDataConnectionAlias(BaseModel):
    success: bool
    data_connection_alias: Optional[
        "CreateDataConnectionAliasCreateDataConnectionAliasDataConnectionAlias"
    ] = Field(alias="dataConnectionAlias")
    message: Optional[str]


class CreateDataConnectionAliasCreateDataConnectionAliasDataConnectionAlias(BaseModel):
    id: str
    dataset_id: str = Field(alias="datasetId")


CreateDataConnectionAlias.model_rebuild()
CreateDataConnectionAliasCreateDataConnectionAlias.model_rebuild()
