# Generated by ariadne-codegen
# Source: ../../apps/frontend/app/api/v1/osograph/schema

from enum import Enum


class MemberRole(str, Enum):
    owner = "owner"
    admin = "admin"


class InvitationStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class DatasetType(str, Enum):
    USER_MODEL = "USER_MODEL"
    DATA_CONNECTOR = "DATA_CONNECTOR"
    DATA_INGESTION = "DATA_INGESTION"
    STATIC_MODEL = "STATIC_MODEL"


class DataIngestionFactoryType(str, Enum):
    REST = "REST"
    GRAPHQL = "GRAPHQL"
    ARCHIVE_DIR = "ARCHIVE_DIR"


class DataModelKind(str, Enum):
    INCREMENTAL_BY_TIME_RANGE = "INCREMENTAL_BY_TIME_RANGE"
    INCREMENTAL_BY_UNIQUE_KEY = "INCREMENTAL_BY_UNIQUE_KEY"
    INCREMENTAL_BY_PARTITION = "INCREMENTAL_BY_PARTITION"
    SCD_TYPE_2_BY_TIME = "SCD_TYPE_2_BY_TIME"
    SCD_TYPE_2_BY_COLUMN = "SCD_TYPE_2_BY_COLUMN"
    FULL = "FULL"
    VIEW = "VIEW"


class RunTriggerType(str, Enum):
    MANUAL = "MANUAL"
    SCHEDULED = "SCHEDULED"


class RunType(str, Enum):
    MANUAL = "MANUAL"
    SCHEDULED = "SCHEDULED"


class RunStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class StepStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
