# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FinishRun(BaseModel):
    finish_run: "FinishRunFinishRun" = Field(alias="finishRun")


class FinishRunFinishRun(BaseModel):
    success: bool
    message: Optional[str]
    run: Optional["FinishRunFinishRunRun"]


class FinishRunFinishRunRun(BaseModel):
    id: str


FinishRun.model_rebuild()
FinishRunFinishRun.model_rebuild()
