# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FinishStep(BaseModel):
    finish_step: "FinishStepFinishStep" = Field(alias="finishStep")


class FinishStepFinishStep(BaseModel):
    success: bool
    message: Optional[str]
    step: Optional["FinishStepFinishStepStep"]


class FinishStepFinishStepStep(BaseModel):
    id: str


FinishStep.model_rebuild()
FinishStepFinishStep.model_rebuild()
