# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Any, List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import DataIngestionFactoryType


class GetDataIngestionConfig(BaseModel):
    datasets: "GetDataIngestionConfigDatasets"


class GetDataIngestionConfigDatasets(BaseModel):
    edges: List["GetDataIngestionConfigDatasetsEdges"]


class GetDataIngestionConfigDatasetsEdges(BaseModel):
    node: "GetDataIngestionConfigDatasetsEdgesNode"


class GetDataIngestionConfigDatasetsEdgesNode(BaseModel):
    id: str
    type_definition: Union[
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataModelDefinition",
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestion",
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataConnector",
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionStaticModelDefinition",
    ] = Field(alias="typeDefinition", discriminator="typename__")


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataModelDefinition(
    BaseModel
):
    typename__: Literal["DataModelDefinition"] = Field(alias="__typename")


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestion(BaseModel):
    typename__: Literal["DataIngestion"] = Field(alias="__typename")
    configs: "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigs"


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigs(
    BaseModel
):
    edges: List[
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigsEdges"
    ]


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigsEdges(
    BaseModel
):
    node: "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigsEdgesNode"


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigsEdgesNode(
    BaseModel
):
    id: str
    dataset_id: str = Field(alias="datasetId")
    factory_type: DataIngestionFactoryType = Field(alias="factoryType")
    config: Any


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataConnector(BaseModel):
    typename__: Literal["DataConnector"] = Field(alias="__typename")


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionStaticModelDefinition(
    BaseModel
):
    typename__: Literal["StaticModelDefinition"] = Field(alias="__typename")


GetDataIngestionConfig.model_rebuild()
GetDataIngestionConfigDatasets.model_rebuild()
GetDataIngestionConfigDatasetsEdges.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNode.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestion.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigs.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionConfigsEdges.model_rebuild()
