# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import DatasetCommon


class GetStaticModels(BaseModel):
    datasets: "GetStaticModelsDatasets"


class GetStaticModelsDatasets(BaseModel):
    edges: List["GetStaticModelsDatasetsEdges"]


class GetStaticModelsDatasetsEdges(BaseModel):
    node: "GetStaticModelsDatasetsEdgesNode"


class GetStaticModelsDatasetsEdgesNode(DatasetCommon):
    type_definition: Union[
        "GetStaticModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition",
        "GetStaticModelsDatasetsEdgesNodeTypeDefinitionDataIngestionDefinition",
        "GetStaticModelsDatasetsEdgesNodeTypeDefinitionDataConnectionDefinition",
        "GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition",
    ] = Field(alias="typeDefinition", discriminator="typename__")


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition(BaseModel):
    typename__: Literal["DataModelDefinition"] = Field(alias="__typename")


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionDataIngestionDefinition(BaseModel):
    typename__: Literal["DataIngestionDefinition"] = Field(alias="__typename")


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionDataConnectionDefinition(BaseModel):
    typename__: Literal["DataConnectionDefinition"] = Field(alias="__typename")


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition(BaseModel):
    typename__: Literal["StaticModelDefinition"] = Field(alias="__typename")
    static_models: "GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModels" = Field(
        alias="staticModels"
    )


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModels(
    BaseModel
):
    edges: List[
        "GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModelsEdges"
    ]


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModelsEdges(
    BaseModel
):
    node: "GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModelsEdgesNode"


class GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModelsEdgesNode(
    BaseModel
):
    id: str
    name: str


GetStaticModels.model_rebuild()
GetStaticModelsDatasets.model_rebuild()
GetStaticModelsDatasetsEdges.model_rebuild()
GetStaticModelsDatasetsEdgesNode.model_rebuild()
GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition.model_rebuild()
GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModels.model_rebuild()
GetStaticModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinitionStaticModelsEdges.model_rebuild()
