# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import DataModelKind


class GetDataModels(BaseModel):
    datasets: "GetDataModelsDatasets"


class GetDataModelsDatasets(BaseModel):
    edges: List["GetDataModelsDatasetsEdges"]


class GetDataModelsDatasetsEdges(BaseModel):
    node: "GetDataModelsDatasetsEdgesNode"


class GetDataModelsDatasetsEdgesNode(BaseModel):
    id: str
    display_name: Optional[str] = Field(alias="displayName")
    description: Optional[str]
    type_definition: Union[
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition",
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataIngestion",
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataConnector",
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition",
    ] = Field(alias="typeDefinition", discriminator="typename__")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition(BaseModel):
    typename__: Literal["DataModelDefinition"] = Field(alias="__typename")
    org_id: str = Field(alias="orgId")
    dataset_id: str = Field(alias="datasetId")
    data_models: "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModels" = Field(
        alias="dataModels"
    )


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModels(
    BaseModel
):
    edges: List[
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdges"
    ]


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdges(
    BaseModel
):
    node: "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNode"


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNode(
    BaseModel
):
    org_id: str = Field(alias="orgId")
    created_at: Any = Field(alias="createdAt")
    is_enabled: bool = Field(alias="isEnabled")
    id: str
    latest_release: Optional[
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestRelease"
    ] = Field(alias="latestRelease")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestRelease(
    BaseModel
):
    id: str
    revision: "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevision"


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevision(
    BaseModel
):
    name: str
    code: str
    depends_on: Optional[
        List[
            "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevisionDependsOn"
        ]
    ] = Field(alias="dependsOn")
    hash: str
    kind: DataModelKind
    kind_options: Optional[
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevisionKindOptions"
    ] = Field(alias="kindOptions")
    partitioned_by: Optional[List[str]] = Field(alias="partitionedBy")
    schema_: Optional[
        List[
            "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevisionSchema"
        ]
    ] = Field(alias="schema")
    start: Optional[Any]
    end: Optional[Any]
    clustered_by: Optional[List[str]] = Field(alias="clusteredBy")
    language: str


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevisionDependsOn(
    BaseModel
):
    alias: Optional[str]
    table_id: str = Field(alias="tableId")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevisionKindOptions(
    BaseModel
):
    time_column: Optional[str] = Field(alias="timeColumn")
    time_column_format: Optional[str] = Field(alias="timeColumnFormat")
    batch_size: Optional[int] = Field(alias="batchSize")
    lookback: Optional[int]
    unique_key_columns: Optional[List[str]] = Field(alias="uniqueKeyColumns")
    when_matched_sql: Optional[str] = Field(alias="whenMatchedSql")
    merge_filter: Optional[str] = Field(alias="mergeFilter")
    valid_from_name: Optional[str] = Field(alias="validFromName")
    valid_to_name: Optional[str] = Field(alias="validToName")
    invalidate_hard_deletes: Optional[bool] = Field(alias="invalidateHardDeletes")
    updated_at_column: Optional[str] = Field(alias="updatedAtColumn")
    updated_at_as_valid_from: Optional[bool] = Field(alias="updatedAtAsValidFrom")
    scd_columns: Optional[List[str]] = Field(alias="scdColumns")
    execution_time_as_valid_from: Optional[bool] = Field(
        alias="executionTimeAsValidFrom"
    )


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevisionSchema(
    BaseModel
):
    name: str
    type: str
    description: Optional[str]


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataIngestion(BaseModel):
    typename__: Literal["DataIngestion"] = Field(alias="__typename")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataConnector(BaseModel):
    typename__: Literal["DataConnector"] = Field(alias="__typename")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition(BaseModel):
    typename__: Literal["StaticModelDefinition"] = Field(alias="__typename")


GetDataModels.model_rebuild()
GetDataModelsDatasets.model_rebuild()
GetDataModelsDatasetsEdges.model_rebuild()
GetDataModelsDatasetsEdgesNode.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModels.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdges.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNode.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestRelease.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModelsEdgesNodeLatestReleaseRevision.model_rebuild()
