# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DataConnectionType
from .fragments import OrganizationCommon


class GetDataConnection(BaseModel):
    data_connections: "GetDataConnectionDataConnections" = Field(
        alias="dataConnections"
    )


class GetDataConnectionDataConnections(BaseModel):
    edges: List["GetDataConnectionDataConnectionsEdges"]


class GetDataConnectionDataConnectionsEdges(BaseModel):
    node: "GetDataConnectionDataConnectionsEdgesNode"


class GetDataConnectionDataConnectionsEdgesNode(BaseModel):
    id: str
    organization: "GetDataConnectionDataConnectionsEdgesNodeOrganization"
    name: str
    type: DataConnectionType


class GetDataConnectionDataConnectionsEdgesNodeOrganization(OrganizationCommon):
    pass


GetDataConnection.model_rebuild()
GetDataConnectionDataConnections.model_rebuild()
GetDataConnectionDataConnectionsEdges.model_rebuild()
GetDataConnectionDataConnectionsEdgesNode.model_rebuild()
