# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import DataModels, DatasetCommon


class GetDataModels(BaseModel):
    datasets: "GetDataModelsDatasets"


class GetDataModelsDatasets(BaseModel):
    edges: List["GetDataModelsDatasetsEdges"]


class GetDataModelsDatasetsEdges(BaseModel):
    node: "GetDataModelsDatasetsEdgesNode"


class GetDataModelsDatasetsEdgesNode(DatasetCommon):
    type_definition: Union[
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition",
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataIngestion",
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataConnector",
        "GetDataModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition",
    ] = Field(alias="typeDefinition", discriminator="typename__")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition(BaseModel):
    typename__: Literal["DataModelDefinition"] = Field(alias="__typename")
    data_models: "GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModels" = Field(
        alias="dataModels"
    )


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinitionDataModels(
    DataModels
):
    pass


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataIngestion(BaseModel):
    typename__: Literal["DataIngestion"] = Field(alias="__typename")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionDataConnector(BaseModel):
    typename__: Literal["DataConnector"] = Field(alias="__typename")


class GetDataModelsDatasetsEdgesNodeTypeDefinitionStaticModelDefinition(BaseModel):
    typename__: Literal["StaticModelDefinition"] = Field(alias="__typename")


GetDataModels.model_rebuild()
GetDataModelsDatasets.model_rebuild()
GetDataModelsDatasetsEdges.model_rebuild()
GetDataModelsDatasetsEdgesNode.model_rebuild()
GetDataModelsDatasetsEdgesNodeTypeDefinitionDataModelDefinition.model_rebuild()
