# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Any, List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import DataIngestionFactoryType
from .fragments import DatasetCommon


class GetDataIngestionConfig(BaseModel):
    datasets: "GetDataIngestionConfigDatasets"


class GetDataIngestionConfigDatasets(BaseModel):
    edges: List["GetDataIngestionConfigDatasetsEdges"]


class GetDataIngestionConfigDatasetsEdges(BaseModel):
    node: "GetDataIngestionConfigDatasetsEdgesNode"


class GetDataIngestionConfigDatasetsEdgesNode(DatasetCommon):
    type_definition: Union[
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataModelDefinition",
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinition",
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataConnector",
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionStaticModelDefinition",
    ] = Field(alias="typeDefinition", discriminator="typename__")


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataModelDefinition(
    BaseModel
):
    typename__: Literal["DataModelDefinition"] = Field(alias="__typename")


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinition(
    BaseModel
):
    typename__: Literal["DataIngestionDefinition"] = Field(alias="__typename")
    data_ingestions: "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestions" = Field(
        alias="dataIngestions"
    )


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestions(
    BaseModel
):
    edges: List[
        "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestionsEdges"
    ]


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestionsEdges(
    BaseModel
):
    node: "GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestionsEdgesNode"


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestionsEdgesNode(
    BaseModel
):
    id: str
    dataset_id: str = Field(alias="datasetId")
    factory_type: DataIngestionFactoryType = Field(alias="factoryType")
    config: Any


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataConnector(BaseModel):
    typename__: Literal["DataConnector"] = Field(alias="__typename")


class GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionStaticModelDefinition(
    BaseModel
):
    typename__: Literal["StaticModelDefinition"] = Field(alias="__typename")


GetDataIngestionConfig.model_rebuild()
GetDataIngestionConfigDatasets.model_rebuild()
GetDataIngestionConfigDatasetsEdges.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNode.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinition.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestions.model_rebuild()
GetDataIngestionConfigDatasetsEdgesNodeTypeDefinitionDataIngestionDefinitionDataIngestionsEdges.model_rebuild()
