# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List

from .base_model import BaseModel


class GetNotebook(BaseModel):
    notebooks: "GetNotebookNotebooks"


class GetNotebookNotebooks(BaseModel):
    edges: List["GetNotebookNotebooksEdges"]


class GetNotebookNotebooksEdges(BaseModel):
    node: "GetNotebookNotebooksEdgesNode"


class GetNotebookNotebooksEdgesNode(BaseModel):
    id: str
    name: str
    data: str


GetNotebook.model_rebuild()
GetNotebookNotebooks.model_rebuild()
GetNotebookNotebooksEdges.model_rebuild()
