# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List

from .base_model import BaseModel
from .fragments import RunCommon


class GetRun(BaseModel):
    runs: "GetRunRuns"


class GetRunRuns(BaseModel):
    edges: List["GetRunRunsEdges"]


class GetRunRunsEdges(BaseModel):
    node: "GetRunRunsEdgesNode"


class GetRunRunsEdgesNode(RunCommon):
    pass


GetRun.model_rebuild()
GetRunRuns.model_rebuild()
GetRunRunsEdges.model_rebuild()
