# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DataConnectionType


class GetDataConnection(BaseModel):
    data_connections: "GetDataConnectionDataConnections" = Field(
        alias="dataConnections"
    )


class GetDataConnectionDataConnections(BaseModel):
    edges: List["GetDataConnectionDataConnectionsEdges"]


class GetDataConnectionDataConnectionsEdges(BaseModel):
    node: "GetDataConnectionDataConnectionsEdgesNode"


class GetDataConnectionDataConnectionsEdgesNode(BaseModel):
    id: str
    org_id: str = Field(alias="orgId")
    name: str
    type: DataConnectionType


GetDataConnection.model_rebuild()
GetDataConnectionDataConnections.model_rebuild()
GetDataConnectionDataConnectionsEdges.model_rebuild()
