# Generated by ariadne-codegen
# Source: ../../apps/frontend/app/api/v1/osograph/schema

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DataIngestionFactoryType,
    DataModelKind,
    DatasetType,
    MemberRole,
    RunStatus,
    StepStatus,
)


class CreateDataIngestionInput(BaseModel):
    dataset_id: str = Field(alias="datasetId")
    factory_type: DataIngestionFactoryType = Field(alias="factoryType")
    config: Any


class CreateDataModelInput(BaseModel):
    org_id: str = Field(alias="orgId")
    dataset_id: str = Field(alias="datasetId")
    name: str
    is_enabled: Optional[bool] = Field(alias="isEnabled", default=None)


class UpdateDataModelInput(BaseModel):
    data_model_id: str = Field(alias="dataModelId")
    name: Optional[str] = None
    is_enabled: Optional[bool] = Field(alias="isEnabled", default=None)


class DataModelColumnInput(BaseModel):
    name: str
    type: str
    description: Optional[str] = None


class DataModelDependencyInput(BaseModel):
    data_model_id: str = Field(alias="dataModelId")
    alias: Optional[str] = None


class DataModelKindOptionsInput(BaseModel):
    time_column: Optional[str] = Field(alias="timeColumn", default=None)
    time_column_format: Optional[str] = Field(alias="timeColumnFormat", default=None)
    batch_size: Optional[int] = Field(alias="batchSize", default=None)
    lookback: Optional[int] = None
    unique_key_columns: Optional[List[str]] = Field(
        alias="uniqueKeyColumns", default=None
    )
    when_matched_sql: Optional[str] = Field(alias="whenMatchedSql", default=None)
    merge_filter: Optional[str] = Field(alias="mergeFilter", default=None)
    valid_from_name: Optional[str] = Field(alias="validFromName", default=None)
    valid_to_name: Optional[str] = Field(alias="validToName", default=None)
    invalidate_hard_deletes: Optional[bool] = Field(
        alias="invalidateHardDeletes", default=None
    )
    updated_at_column: Optional[str] = Field(alias="updatedAtColumn", default=None)
    updated_at_as_valid_from: Optional[bool] = Field(
        alias="updatedAtAsValidFrom", default=None
    )
    scd_columns: Optional[List[str]] = Field(alias="scdColumns", default=None)
    execution_time_as_valid_from: Optional[bool] = Field(
        alias="executionTimeAsValidFrom", default=None
    )


class CreateDataModelRevisionInput(BaseModel):
    data_model_id: str = Field(alias="dataModelId")
    name: str
    description: Optional[str] = None
    language: str
    code: str
    cron: str
    start: Optional[Any] = None
    end: Optional[Any] = None
    schema_: List["DataModelColumnInput"] = Field(alias="schema")
    depends_on: Optional[List["DataModelDependencyInput"]] = Field(
        alias="dependsOn", default=None
    )
    partitioned_by: Optional[List[str]] = Field(alias="partitionedBy", default=None)
    clustered_by: Optional[List[str]] = Field(alias="clusteredBy", default=None)
    kind: DataModelKind
    kind_options: Optional["DataModelKindOptionsInput"] = Field(
        alias="kindOptions", default=None
    )


class CreateDataModelReleaseInput(BaseModel):
    data_model_id: str = Field(alias="dataModelId")
    data_model_revision_id: str = Field(alias="dataModelRevisionId")
    description: Optional[str] = None


class CreateDatasetInput(BaseModel):
    org_id: str = Field(alias="orgId")
    name: str
    display_name: Optional[str] = Field(alias="displayName", default=None)
    description: Optional[str] = None
    type: Optional[DatasetType] = DatasetType.USER_MODEL
    is_public: Optional[bool] = Field(alias="isPublic", default=False)


class UpdateDatasetInput(BaseModel):
    id: str
    name: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    description: Optional[str] = None
    is_public: Optional[bool] = Field(alias="isPublic", default=None)


class CreateInvitationInput(BaseModel):
    org_id: str = Field(alias="orgId")
    email: str
    role: MemberRole = MemberRole.admin


class AcceptInvitationInput(BaseModel):
    invitation_id: str = Field(alias="invitationId")


class RevokeInvitationInput(BaseModel):
    invitation_id: str = Field(alias="invitationId")


class CreateNotebookInput(BaseModel):
    org_id: str = Field(alias="orgId")
    name: str
    description: Optional[str] = None


class UpdateNotebookInput(BaseModel):
    id: str
    name: Optional[str] = None
    description: Optional[str] = None


class SaveNotebookPreviewInput(BaseModel):
    notebook_id: str = Field(alias="notebookId")
    preview: str


class AddUserByEmailInput(BaseModel):
    org_id: str = Field(alias="orgId")
    email: str
    role: MemberRole


class RemoveMemberInput(BaseModel):
    org_id: str = Field(alias="orgId")
    user_id: str = Field(alias="userId")


class UpdateMemberRoleInput(BaseModel):
    org_id: str = Field(alias="orgId")
    user_id: str = Field(alias="userId")
    role: MemberRole


class CreateUserModelRunRequestInput(BaseModel):
    dataset_id: str = Field(alias="datasetId")
    selected_models: Optional[List[str]] = Field(alias="selectedModels", default=None)


class CreateDataIngestionRunRequestInput(BaseModel):
    dataset_id: str = Field(alias="datasetId")


class CreateDataConnectorRunRequestInput(BaseModel):
    dataset_id: str = Field(alias="datasetId")


class CreateStaticModelRunRequestInput(BaseModel):
    dataset_id: str = Field(alias="datasetId")
    selected_models: Optional[List[str]] = Field(alias="selectedModels", default=None)


class CancelRunInput(BaseModel):
    run_id: str = Field(alias="runId")


class CreateStaticModelInput(BaseModel):
    org_id: str = Field(alias="orgId")
    dataset_id: str = Field(alias="datasetId")
    name: str


class UpdateStaticModelInput(BaseModel):
    static_model_id: str = Field(alias="staticModelId")
    name: Optional[str] = None


class StartRunInput(BaseModel):
    run_id: str = Field(alias="runId")


class UpdateMetadataInput(BaseModel):
    value: Any
    merge: Optional[bool] = False


class UpdateRunMetadataInput(BaseModel):
    run_id: str = Field(alias="runId")
    metadata: "UpdateMetadataInput"


class FinishRunInput(BaseModel):
    run_id: str = Field(alias="runId")
    status: RunStatus
    status_code: int = Field(alias="statusCode")
    logs_url: str = Field(alias="logsUrl")
    metadata: Optional["UpdateMetadataInput"] = None


class StartStepInput(BaseModel):
    run_id: str = Field(alias="runId")
    name: str
    display_name: str = Field(alias="displayName")


class FinishStepInput(BaseModel):
    step_id: str = Field(alias="stepId")
    status: StepStatus
    logs_url: str = Field(alias="logsUrl")


class CreateMaterializationInput(BaseModel):
    step_id: str = Field(alias="stepId")
    table_id: str = Field(alias="tableId")
    warehouse_fqn: str = Field(alias="warehouseFqn")
    schema_: List["DataModelColumnInput"] = Field(alias="schema")


CreateDataModelRevisionInput.model_rebuild()
UpdateRunMetadataInput.model_rebuild()
FinishRunInput.model_rebuild()
CreateMaterializationInput.model_rebuild()
