# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class ResolveTables(BaseModel):
    system: "ResolveTablesSystem"


class ResolveTablesSystem(BaseModel):
    resolve_tables: List["ResolveTablesSystemResolveTables"] = Field(
        alias="resolveTables"
    )


class ResolveTablesSystemResolveTables(BaseModel):
    reference: str
    fqn: str


ResolveTables.model_rebuild()
ResolveTablesSystem.model_rebuild()
