# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from pydantic import Field

from .base_model import BaseModel


class SavePublishedNotebookHtml(BaseModel):
    save_published_notebook_html: "SavePublishedNotebookHtmlSavePublishedNotebookHtml" = Field(
        alias="savePublishedNotebookHtml"
    )


class SavePublishedNotebookHtmlSavePublishedNotebookHtml(BaseModel):
    success: bool


SavePublishedNotebookHtml.model_rebuild()
