# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class StartStep(BaseModel):
    start_step: "StartStepStartStep" = Field(alias="startStep")


class StartStepStartStep(BaseModel):
    success: bool
    message: Optional[str]
    step: "StartStepStartStepStep"


class StartStepStartStepStep(BaseModel):
    id: str


StartStep.model_rebuild()
StartStepStartStep.model_rebuild()
