# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from pydantic import Field

from .base_model import BaseModel


class StartRun(BaseModel):
    start_run: "StartRunStartRun" = Field(alias="startRun")


class StartRunStartRun(BaseModel):
    success: bool


StartRun.model_rebuild()
