# Generated by ariadne-codegen
# Source: scheduler/client.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateRunMetadata(BaseModel):
    update_run_metadata: "UpdateRunMetadataUpdateRunMetadata" = Field(
        alias="updateRunMetadata"
    )


class UpdateRunMetadataUpdateRunMetadata(BaseModel):
    success: bool
    message: Optional[str]
    run: Optional["UpdateRunMetadataUpdateRunMetadataRun"]


class UpdateRunMetadataUpdateRunMetadataRun(BaseModel):
    id: str


UpdateRunMetadata.model_rebuild()
UpdateRunMetadataUpdateRunMetadata.model_rebuild()
