// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: publish-notebook.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

/** A request to generate the static html for a notebook */
export interface PublishNotebookRunRequest {
  runId: Uint8Array;
  /** The notebook id to be generated */
  notebookId: string;
  /** OSO API key to run the pyoso queries in the notebook */
  osoApiKey: string;
}

function createBasePublishNotebookRunRequest(): PublishNotebookRunRequest {
  return { runId: new Uint8Array(0), notebookId: "", osoApiKey: "" };
}

export const PublishNotebookRunRequest: MessageFns<PublishNotebookRunRequest> =
  {
    encode(
      message: PublishNotebookRunRequest,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.runId.length !== 0) {
        writer.uint32(10).bytes(message.runId);
      }
      if (message.notebookId !== "") {
        writer.uint32(18).string(message.notebookId);
      }
      if (message.osoApiKey !== "") {
        writer.uint32(26).string(message.osoApiKey);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): PublishNotebookRunRequest {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePublishNotebookRunRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.runId = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.notebookId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.osoApiKey = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): PublishNotebookRunRequest {
      return {
        runId: isSet(object.runId)
          ? bytesFromBase64(object.runId)
          : new Uint8Array(0),
        notebookId: isSet(object.notebookId)
          ? globalThis.String(object.notebookId)
          : "",
        osoApiKey: isSet(object.osoApiKey)
          ? globalThis.String(object.osoApiKey)
          : "",
      };
    },

    toJSON(message: PublishNotebookRunRequest): unknown {
      const obj: any = {};
      if (message.runId.length !== 0) {
        obj.runId = base64FromBytes(message.runId);
      }
      if (message.notebookId !== "") {
        obj.notebookId = message.notebookId;
      }
      if (message.osoApiKey !== "") {
        obj.osoApiKey = message.osoApiKey;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<PublishNotebookRunRequest>, I>>(
      base?: I,
    ): PublishNotebookRunRequest {
      return PublishNotebookRunRequest.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<PublishNotebookRunRequest>, I>>(
      object: I,
    ): PublishNotebookRunRequest {
      const message = createBasePublishNotebookRunRequest();
      message.runId = object.runId ?? new Uint8Array(0);
      message.notebookId = object.notebookId ?? "";
      message.osoApiKey = object.osoApiKey ?? "";
      return message;
    },
  };

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
