// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

/**
 * A request to run a query on the trino cluster. The results will be stored
 * and can be retrieved later using the request_id.
 */
export interface QueryRunRequest {
  runId: Uint8Array;
  /**
   * The query should be sent as is to the workers. Any rewriting will be
   * handled at the worker
   */
  query: string;
  /**
   * The user making the request. This is used to authenticate the
   * request and authorize access to the data on trino.
   */
  user: string;
  /**
   * Metadata passed on to the workers for query rewriting inference. This is
   * expected to be a JSON string.
   */
  metadataJson: string;
}

function createBaseQueryRunRequest(): QueryRunRequest {
  return { runId: new Uint8Array(0), query: "", user: "", metadataJson: "" };
}

export const QueryRunRequest: MessageFns<QueryRunRequest> = {
  encode(
    message: QueryRunRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.runId.length !== 0) {
      writer.uint32(10).bytes(message.runId);
    }
    if (message.query !== "") {
      writer.uint32(18).string(message.query);
    }
    if (message.user !== "") {
      writer.uint32(26).string(message.user);
    }
    if (message.metadataJson !== "") {
      writer.uint32(34).string(message.metadataJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryRunRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.metadataJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryRunRequest {
    return {
      runId: isSet(object.runId)
        ? bytesFromBase64(object.runId)
        : new Uint8Array(0),
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      user: isSet(object.user) ? globalThis.String(object.user) : "",
      metadataJson: isSet(object.metadataJson)
        ? globalThis.String(object.metadataJson)
        : "",
    };
  },

  toJSON(message: QueryRunRequest): unknown {
    const obj: any = {};
    if (message.runId.length !== 0) {
      obj.runId = base64FromBytes(message.runId);
    }
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.user !== "") {
      obj.user = message.user;
    }
    if (message.metadataJson !== "") {
      obj.metadataJson = message.metadataJson;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryRunRequest>, I>>(
    base?: I,
  ): QueryRunRequest {
    return QueryRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryRunRequest>, I>>(
    object: I,
  ): QueryRunRequest {
    const message = createBaseQueryRunRequest();
    message.runId = object.runId ?? new Uint8Array(0);
    message.query = object.query ?? "";
    message.user = object.user ?? "";
    message.metadataJson = object.metadataJson ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
