/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schema";
export type Json = z.infer<typeof generated.jsonSchema>;
export type AdminUsersRow = z.infer<typeof generated.adminUsersRowSchema>;
export type AdminUsersInsert = z.infer<typeof generated.adminUsersInsertSchema>;
export type AdminUsersUpdate = z.infer<typeof generated.adminUsersUpdateSchema>;
export type AdminUsersRelationships = z.infer<
  typeof generated.adminUsersRelationshipsSchema
>;
export type ApiKeysRow = z.infer<typeof generated.apiKeysRowSchema>;
export type ApiKeysInsert = z.infer<typeof generated.apiKeysInsertSchema>;
export type ApiKeysUpdate = z.infer<typeof generated.apiKeysUpdateSchema>;
export type ApiKeysRelationships = z.infer<
  typeof generated.apiKeysRelationshipsSchema
>;
export type CreditTransactionsRow = z.infer<
  typeof generated.creditTransactionsRowSchema
>;
export type CreditTransactionsInsert = z.infer<
  typeof generated.creditTransactionsInsertSchema
>;
export type CreditTransactionsUpdate = z.infer<
  typeof generated.creditTransactionsUpdateSchema
>;
export type DynamicConnectorsRow = z.infer<
  typeof generated.dynamicConnectorsRowSchema
>;
export type DynamicConnectorsInsert = z.infer<
  typeof generated.dynamicConnectorsInsertSchema
>;
export type DynamicConnectorsUpdate = z.infer<
  typeof generated.dynamicConnectorsUpdateSchema
>;
export type DynamicConnectorsRelationships = z.infer<
  typeof generated.dynamicConnectorsRelationshipsSchema
>;
export type OrganizationsRow = z.infer<typeof generated.organizationsRowSchema>;
export type OrganizationsInsert = z.infer<
  typeof generated.organizationsInsertSchema
>;
export type OrganizationsUpdate = z.infer<
  typeof generated.organizationsUpdateSchema
>;
export type OrganizationsRelationships = z.infer<
  typeof generated.organizationsRelationshipsSchema
>;
export type UserCreditsRow = z.infer<typeof generated.userCreditsRowSchema>;
export type UserCreditsInsert = z.infer<
  typeof generated.userCreditsInsertSchema
>;
export type UserCreditsUpdate = z.infer<
  typeof generated.userCreditsUpdateSchema
>;
export type UserProfilesRow = z.infer<typeof generated.userProfilesRowSchema>;
export type UserProfilesInsert = z.infer<
  typeof generated.userProfilesInsertSchema
>;
export type UserProfilesUpdate = z.infer<
  typeof generated.userProfilesUpdateSchema
>;
export type UsersByOrganizationRow = z.infer<
  typeof generated.usersByOrganizationRowSchema
>;
export type UsersByOrganizationInsert = z.infer<
  typeof generated.usersByOrganizationInsertSchema
>;
export type UsersByOrganizationUpdate = z.infer<
  typeof generated.usersByOrganizationUpdateSchema
>;
export type UsersByOrganizationRelationships = z.infer<
  typeof generated.usersByOrganizationRelationshipsSchema
>;
export type AddCreditsArgs = z.infer<typeof generated.addCreditsArgsSchema>;
export type AddCreditsReturns = z.infer<
  typeof generated.addCreditsReturnsSchema
>;
export type DeductCreditsArgs = z.infer<
  typeof generated.deductCreditsArgsSchema
>;
export type DeductCreditsReturns = z.infer<
  typeof generated.deductCreditsReturnsSchema
>;
export type GetUserCreditsArgs = z.infer<
  typeof generated.getUserCreditsArgsSchema
>;
export type GetUserCreditsReturns = z.infer<
  typeof generated.getUserCreditsReturnsSchema
>;
export type HasuraTokenHookArgs = z.infer<
  typeof generated.hasuraTokenHookArgsSchema
>;
export type HasuraTokenHookReturns = z.infer<
  typeof generated.hasuraTokenHookReturnsSchema
>;
export type PreviewDeductCreditsArgs = z.infer<
  typeof generated.previewDeductCreditsArgsSchema
>;
export type PreviewDeductCreditsReturns = z.infer<
  typeof generated.previewDeductCreditsReturnsSchema
>;
