/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "@/lib/types/supabase";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const adminUsersRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.number(),
  name: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const adminUsersInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const adminUsersUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const adminUsersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("admin_users_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const apiKeysRowSchema = z.object({
  api_key: z.string(),
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const apiKeysInsertSchema = z.object({
  api_key: z.string(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const apiKeysUpdateSchema = z.object({
  api_key: z.string().optional(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const apiKeysRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("api_keys_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("api_keys_user_id_fkey1"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const chatHistoryRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  data: z.string().nullable(),
  deleted_at: z.string().nullable(),
  display_name: z.string(),
  id: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const chatHistoryInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  display_name: z.string(),
  id: z.string().optional(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const chatHistoryUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  display_name: z.string().optional(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const chatHistoryRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("chat_history_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("chat_history_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const connectorRelationshipsRowSchema = z.object({
  id: z.string(),
  org_id: z.string(),
  source_column_name: z.string(),
  source_table_id: z.string(),
  target_column_name: z.string().nullable(),
  target_oso_entity: z.string().nullable(),
  target_table_id: z.string().nullable(),
});

export const connectorRelationshipsInsertSchema = z.object({
  id: z.string().optional(),
  org_id: z.string(),
  source_column_name: z.string(),
  source_table_id: z.string(),
  target_column_name: z.string().optional().nullable(),
  target_oso_entity: z.string().optional().nullable(),
  target_table_id: z.string().optional().nullable(),
});

export const connectorRelationshipsUpdateSchema = z.object({
  id: z.string().optional(),
  org_id: z.string().optional(),
  source_column_name: z.string().optional(),
  source_table_id: z.string().optional(),
  target_column_name: z.string().optional().nullable(),
  target_oso_entity: z.string().optional().nullable(),
  target_table_id: z.string().optional().nullable(),
});

export const connectorRelationshipsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_org_id"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_source_column"),
    columns: z.tuple([
      z.literal("source_table_id"),
      z.literal("source_column_name"),
    ]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_column_contexts"),
    referencedColumns: z.tuple([
      z.literal("table_id"),
      z.literal("column_name"),
    ]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_source_table"),
    columns: z.tuple([z.literal("source_table_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_table_contexts"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_target_column"),
    columns: z.tuple([
      z.literal("target_table_id"),
      z.literal("target_column_name"),
    ]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_column_contexts"),
    referencedColumns: z.tuple([
      z.literal("table_id"),
      z.literal("column_name"),
    ]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_target_table"),
    columns: z.tuple([z.literal("target_table_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_table_contexts"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const creditTransactionsRowSchema = z.object({
  amount: z.number(),
  api_endpoint: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  transaction_type: z.string(),
  user_id: z.string(),
});

export const creditTransactionsInsertSchema = z.object({
  amount: z.number(),
  api_endpoint: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  transaction_type: z.string(),
  user_id: z.string(),
});

export const creditTransactionsUpdateSchema = z.object({
  amount: z.number().optional(),
  api_endpoint: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  transaction_type: z.string().optional(),
  user_id: z.string().optional(),
});

export const dynamicColumnContextsRowSchema = z.object({
  column_name: z.string(),
  data_type: z.string(),
  description: z.string().nullable(),
  sample_data: z.string().nullable(),
  table_id: z.string(),
});

export const dynamicColumnContextsInsertSchema = z.object({
  column_name: z.string(),
  data_type: z.string(),
  description: z.string().optional().nullable(),
  sample_data: z.string().optional().nullable(),
  table_id: z.string(),
});

export const dynamicColumnContextsUpdateSchema = z.object({
  column_name: z.string().optional(),
  data_type: z.string().optional(),
  description: z.string().optional().nullable(),
  sample_data: z.string().optional().nullable(),
  table_id: z.string().optional(),
});

export const dynamicColumnContextsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_table_context"),
    columns: z.tuple([z.literal("table_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_table_contexts"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const dynamicConnectorsRowSchema = z.object({
  config: jsonSchema.nullable(),
  connector_name: z.string(),
  connector_type: z.string(),
  created_at: z.string(),
  created_by: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  is_public: z.boolean().nullable(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const dynamicConnectorsInsertSchema = z.object({
  config: jsonSchema.optional().nullable(),
  connector_name: z.string(),
  connector_type: z.string(),
  created_at: z.string().optional(),
  created_by: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional().nullable(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const dynamicConnectorsUpdateSchema = z.object({
  config: jsonSchema.optional().nullable(),
  connector_name: z.string().optional(),
  connector_type: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional().nullable(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const dynamicConnectorsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_org_id"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const dynamicReplicationsRowSchema = z.object({
  config: jsonSchema,
  created_at: z.string(),
  created_by: z.string(),
  credentials_path: z.string().nullable(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  org_id: z.string(),
  replication_name: z.string(),
  replication_type: z.string(),
  updated_at: z.string(),
});

export const dynamicReplicationsInsertSchema = z.object({
  config: jsonSchema,
  created_at: z.string().optional(),
  created_by: z.string(),
  credentials_path: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string(),
  replication_name: z.string(),
  replication_type: z.string(),
  updated_at: z.string().optional(),
});

export const dynamicReplicationsUpdateSchema = z.object({
  config: jsonSchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credentials_path: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  replication_name: z.string().optional(),
  replication_type: z.string().optional(),
  updated_at: z.string().optional(),
});

export const dynamicReplicationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_org_id"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const dynamicTableContextsRowSchema = z.object({
  connector_id: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  table_name: z.string(),
});

export const dynamicTableContextsInsertSchema = z.object({
  connector_id: z.string(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  table_name: z.string(),
});

export const dynamicTableContextsUpdateSchema = z.object({
  connector_id: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  table_name: z.string().optional(),
});

export const dynamicTableContextsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_connector_id"),
    columns: z.tuple([z.literal("connector_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_connectors"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const notebooksRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  data: z.string().nullable(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  notebook_name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const notebooksInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const notebooksUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const notebooksRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("saved_queries_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("saved_queries_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const organizationCreditTransactionsRowSchema = z.object({
  amount: z.number(),
  api_endpoint: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  org_id: z.string(),
  transaction_type: z.string(),
  user_id: z.string(),
});

export const organizationCreditTransactionsInsertSchema = z.object({
  amount: z.number(),
  api_endpoint: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string(),
  transaction_type: z.string(),
  user_id: z.string(),
});

export const organizationCreditTransactionsUpdateSchema = z.object({
  amount: z.number().optional(),
  api_endpoint: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string().optional(),
  transaction_type: z.string().optional(),
  user_id: z.string().optional(),
});

export const organizationCreditTransactionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organization_credit_transactions_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const organizationCreditsRowSchema = z.object({
  created_at: z.string(),
  credits_balance: z.number(),
  id: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const organizationCreditsInsertSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const organizationCreditsUpdateSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const organizationCreditsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organization_credits_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const organizationsRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  org_name: z.string(),
  updated_at: z.string(),
});

export const organizationsInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_name: z.string(),
  updated_at: z.string().optional(),
});

export const organizationsUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const organizationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organizations_created_by_fkey1"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const purchaseIntentsRowSchema = z.object({
  completed_at: z.string().nullable(),
  created_at: z.string(),
  credits_amount: z.number(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  org_id: z.string().nullable(),
  package_id: z.string(),
  price_cents: z.number(),
  status: z.string(),
  stripe_session_id: z.string(),
  user_id: z.string(),
});

export const purchaseIntentsInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  credits_amount: z.number(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string().optional().nullable(),
  package_id: z.string(),
  price_cents: z.number(),
  status: z.string().optional(),
  stripe_session_id: z.string(),
  user_id: z.string(),
});

export const purchaseIntentsUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  credits_amount: z.number().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string().optional().nullable(),
  package_id: z.string().optional(),
  price_cents: z.number().optional(),
  status: z.string().optional(),
  stripe_session_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const purchaseIntentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("purchase_intents_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const reservedNamesRowSchema = z.object({
  created_at: z.string(),
  name: z.string(),
});

export const reservedNamesInsertSchema = z.object({
  created_at: z.string().optional(),
  name: z.string(),
});

export const reservedNamesUpdateSchema = z.object({
  created_at: z.string().optional(),
  name: z.string().optional(),
});

export const userCreditsRowSchema = z.object({
  created_at: z.string(),
  credits_balance: z.number(),
  id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const userCreditsInsertSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const userCreditsUpdateSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const userProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  email: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  updated_at: z.string().nullable(),
  website: z.string().nullable(),
});

export const userProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string(),
  updated_at: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const userProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const usersByOrganizationRowSchema = z.object({
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
  user_role: z.string(),
});

export const usersByOrganizationInsertSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
  user_role: z.string(),
});

export const usersByOrganizationUpdateSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  user_role: z.string().optional(),
});

export const usersByOrganizationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("users_by_organization_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("users_by_organization_user_id_fkey1"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const addCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_metadata: jsonSchema.optional(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const addCreditsReturnsSchema = z.boolean();

export const addOrganizationCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_metadata: jsonSchema.optional(),
  p_org_id: z.string(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const addOrganizationCreditsReturnsSchema = z.boolean();

export const deductCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_api_endpoint: z.string().optional(),
  p_metadata: jsonSchema.optional(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const deductCreditsReturnsSchema = z.boolean();

export const deductOrganizationCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_api_endpoint: z.string().optional(),
  p_metadata: jsonSchema.optional(),
  p_org_id: z.string(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const deductOrganizationCreditsReturnsSchema = z.boolean();

export const getOrganizationCreditsArgsSchema = z.object({
  p_org_id: z.string(),
});

export const getOrganizationCreditsReturnsSchema = z.number();

export const getUserCreditsArgsSchema = z.object({
  p_user_id: z.string(),
});

export const getUserCreditsReturnsSchema = z.number();

export const hasuraTokenHookArgsSchema = z.object({
  event: jsonSchema,
});

export const hasuraTokenHookReturnsSchema = jsonSchema;

export const previewDeductCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_api_endpoint: z.string().optional(),
  p_metadata: jsonSchema.optional(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const previewDeductCreditsReturnsSchema = z.boolean();

export const previewDeductOrganizationCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_api_endpoint: z.string().optional(),
  p_metadata: jsonSchema.optional(),
  p_org_id: z.string(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const previewDeductOrganizationCreditsReturnsSchema = z.boolean();
