/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "@/lib/types/schema";
export type PublicModelKind = z.infer<typeof generated.publicModelKindSchema>;
export type PublicModelRunStatus = z.infer<
  typeof generated.publicModelRunStatusSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type AdminUsersRow = z.infer<typeof generated.adminUsersRowSchema>;
export type AdminUsersInsert = z.infer<typeof generated.adminUsersInsertSchema>;
export type AdminUsersUpdate = z.infer<typeof generated.adminUsersUpdateSchema>;
export type AdminUsersRelationships = z.infer<
  typeof generated.adminUsersRelationshipsSchema
>;
export type ApiKeysRow = z.infer<typeof generated.apiKeysRowSchema>;
export type ApiKeysInsert = z.infer<typeof generated.apiKeysInsertSchema>;
export type ApiKeysUpdate = z.infer<typeof generated.apiKeysUpdateSchema>;
export type ApiKeysRelationships = z.infer<
  typeof generated.apiKeysRelationshipsSchema
>;
export type ChatHistoryRow = z.infer<typeof generated.chatHistoryRowSchema>;
export type ChatHistoryInsert = z.infer<
  typeof generated.chatHistoryInsertSchema
>;
export type ChatHistoryUpdate = z.infer<
  typeof generated.chatHistoryUpdateSchema
>;
export type ChatHistoryRelationships = z.infer<
  typeof generated.chatHistoryRelationshipsSchema
>;
export type ConnectorRelationshipsRow = z.infer<
  typeof generated.connectorRelationshipsRowSchema
>;
export type ConnectorRelationshipsInsert = z.infer<
  typeof generated.connectorRelationshipsInsertSchema
>;
export type ConnectorRelationshipsUpdate = z.infer<
  typeof generated.connectorRelationshipsUpdateSchema
>;
export type ConnectorRelationshipsRelationships = z.infer<
  typeof generated.connectorRelationshipsRelationshipsSchema
>;
export type DatasetsRow = z.infer<typeof generated.datasetsRowSchema>;
export type DatasetsInsert = z.infer<typeof generated.datasetsInsertSchema>;
export type DatasetsUpdate = z.infer<typeof generated.datasetsUpdateSchema>;
export type DatasetsRelationships = z.infer<
  typeof generated.datasetsRelationshipsSchema
>;
export type DatasetsByOrganizationRow = z.infer<
  typeof generated.datasetsByOrganizationRowSchema
>;
export type DatasetsByOrganizationInsert = z.infer<
  typeof generated.datasetsByOrganizationInsertSchema
>;
export type DatasetsByOrganizationUpdate = z.infer<
  typeof generated.datasetsByOrganizationUpdateSchema
>;
export type DatasetsByOrganizationRelationships = z.infer<
  typeof generated.datasetsByOrganizationRelationshipsSchema
>;
export type DynamicColumnContextsRow = z.infer<
  typeof generated.dynamicColumnContextsRowSchema
>;
export type DynamicColumnContextsInsert = z.infer<
  typeof generated.dynamicColumnContextsInsertSchema
>;
export type DynamicColumnContextsUpdate = z.infer<
  typeof generated.dynamicColumnContextsUpdateSchema
>;
export type DynamicColumnContextsRelationships = z.infer<
  typeof generated.dynamicColumnContextsRelationshipsSchema
>;
export type DynamicConnectorsRow = z.infer<
  typeof generated.dynamicConnectorsRowSchema
>;
export type DynamicConnectorsInsert = z.infer<
  typeof generated.dynamicConnectorsInsertSchema
>;
export type DynamicConnectorsUpdate = z.infer<
  typeof generated.dynamicConnectorsUpdateSchema
>;
export type DynamicConnectorsRelationships = z.infer<
  typeof generated.dynamicConnectorsRelationshipsSchema
>;
export type DynamicReplicationsRow = z.infer<
  typeof generated.dynamicReplicationsRowSchema
>;
export type DynamicReplicationsInsert = z.infer<
  typeof generated.dynamicReplicationsInsertSchema
>;
export type DynamicReplicationsUpdate = z.infer<
  typeof generated.dynamicReplicationsUpdateSchema
>;
export type DynamicReplicationsRelationships = z.infer<
  typeof generated.dynamicReplicationsRelationshipsSchema
>;
export type DynamicTableContextsRow = z.infer<
  typeof generated.dynamicTableContextsRowSchema
>;
export type DynamicTableContextsInsert = z.infer<
  typeof generated.dynamicTableContextsInsertSchema
>;
export type DynamicTableContextsUpdate = z.infer<
  typeof generated.dynamicTableContextsUpdateSchema
>;
export type DynamicTableContextsRelationships = z.infer<
  typeof generated.dynamicTableContextsRelationshipsSchema
>;
export type InvitationsRow = z.infer<typeof generated.invitationsRowSchema>;
export type InvitationsInsert = z.infer<
  typeof generated.invitationsInsertSchema
>;
export type InvitationsUpdate = z.infer<
  typeof generated.invitationsUpdateSchema
>;
export type InvitationsRelationships = z.infer<
  typeof generated.invitationsRelationshipsSchema
>;
export type ModelRow = z.infer<typeof generated.modelRowSchema>;
export type ModelInsert = z.infer<typeof generated.modelInsertSchema>;
export type ModelUpdate = z.infer<typeof generated.modelUpdateSchema>;
export type ModelRelationships = z.infer<
  typeof generated.modelRelationshipsSchema
>;
export type ModelReleaseRow = z.infer<typeof generated.modelReleaseRowSchema>;
export type ModelReleaseInsert = z.infer<
  typeof generated.modelReleaseInsertSchema
>;
export type ModelReleaseUpdate = z.infer<
  typeof generated.modelReleaseUpdateSchema
>;
export type ModelReleaseRelationships = z.infer<
  typeof generated.modelReleaseRelationshipsSchema
>;
export type PublicModelDependencyType = z.infer<
  typeof generated.publicModelDependencyTypeSchema
>;
export type PublicModelKindOptions = z.infer<
  typeof generated.publicModelKindOptionsSchema
>;
export type PublicModelColumnType = z.infer<
  typeof generated.publicModelColumnTypeSchema
>;
export type ModelRevisionInsert = z.infer<
  typeof generated.modelRevisionInsertSchema
>;
export type ModelRevisionUpdate = z.infer<
  typeof generated.modelRevisionUpdateSchema
>;
export type ModelRevisionRelationships = z.infer<
  typeof generated.modelRevisionRelationshipsSchema
>;
export type ModelRunRow = z.infer<typeof generated.modelRunRowSchema>;
export type ModelRunInsert = z.infer<typeof generated.modelRunInsertSchema>;
export type ModelRunUpdate = z.infer<typeof generated.modelRunUpdateSchema>;
export type ModelRunRelationships = z.infer<
  typeof generated.modelRunRelationshipsSchema
>;
export type NotebooksRow = z.infer<typeof generated.notebooksRowSchema>;
export type NotebooksInsert = z.infer<typeof generated.notebooksInsertSchema>;
export type NotebooksUpdate = z.infer<typeof generated.notebooksUpdateSchema>;
export type NotebooksRelationships = z.infer<
  typeof generated.notebooksRelationshipsSchema
>;
export type OrganizationCreditTransactionsRow = z.infer<
  typeof generated.organizationCreditTransactionsRowSchema
>;
export type OrganizationCreditTransactionsInsert = z.infer<
  typeof generated.organizationCreditTransactionsInsertSchema
>;
export type OrganizationCreditTransactionsUpdate = z.infer<
  typeof generated.organizationCreditTransactionsUpdateSchema
>;
export type OrganizationCreditTransactionsRelationships = z.infer<
  typeof generated.organizationCreditTransactionsRelationshipsSchema
>;
export type OrganizationCreditsRow = z.infer<
  typeof generated.organizationCreditsRowSchema
>;
export type OrganizationCreditsInsert = z.infer<
  typeof generated.organizationCreditsInsertSchema
>;
export type OrganizationCreditsUpdate = z.infer<
  typeof generated.organizationCreditsUpdateSchema
>;
export type OrganizationCreditsRelationships = z.infer<
  typeof generated.organizationCreditsRelationshipsSchema
>;
export type OrganizationsRow = z.infer<typeof generated.organizationsRowSchema>;
export type OrganizationsInsert = z.infer<
  typeof generated.organizationsInsertSchema
>;
export type OrganizationsUpdate = z.infer<
  typeof generated.organizationsUpdateSchema
>;
export type OrganizationsRelationships = z.infer<
  typeof generated.organizationsRelationshipsSchema
>;
export type PricingPlanRow = z.infer<typeof generated.pricingPlanRowSchema>;
export type PricingPlanInsert = z.infer<
  typeof generated.pricingPlanInsertSchema
>;
export type PricingPlanUpdate = z.infer<
  typeof generated.pricingPlanUpdateSchema
>;
export type PublishedNotebooksRow = z.infer<
  typeof generated.publishedNotebooksRowSchema
>;
export type PublishedNotebooksInsert = z.infer<
  typeof generated.publishedNotebooksInsertSchema
>;
export type PublishedNotebooksUpdate = z.infer<
  typeof generated.publishedNotebooksUpdateSchema
>;
export type PublishedNotebooksRelationships = z.infer<
  typeof generated.publishedNotebooksRelationshipsSchema
>;
export type PurchaseIntentsRow = z.infer<
  typeof generated.purchaseIntentsRowSchema
>;
export type PurchaseIntentsInsert = z.infer<
  typeof generated.purchaseIntentsInsertSchema
>;
export type PurchaseIntentsUpdate = z.infer<
  typeof generated.purchaseIntentsUpdateSchema
>;
export type PurchaseIntentsRelationships = z.infer<
  typeof generated.purchaseIntentsRelationshipsSchema
>;
export type ReservedNamesRow = z.infer<typeof generated.reservedNamesRowSchema>;
export type ReservedNamesInsert = z.infer<
  typeof generated.reservedNamesInsertSchema
>;
export type ReservedNamesUpdate = z.infer<
  typeof generated.reservedNamesUpdateSchema
>;
export type ResourcePermissionsRow = z.infer<
  typeof generated.resourcePermissionsRowSchema
>;
export type ResourcePermissionsInsert = z.infer<
  typeof generated.resourcePermissionsInsertSchema
>;
export type ResourcePermissionsUpdate = z.infer<
  typeof generated.resourcePermissionsUpdateSchema
>;
export type ResourcePermissionsRelationships = z.infer<
  typeof generated.resourcePermissionsRelationshipsSchema
>;
export type UserCreditsRow = z.infer<typeof generated.userCreditsRowSchema>;
export type UserCreditsInsert = z.infer<
  typeof generated.userCreditsInsertSchema
>;
export type UserCreditsUpdate = z.infer<
  typeof generated.userCreditsUpdateSchema
>;
export type UserProfilesRow = z.infer<typeof generated.userProfilesRowSchema>;
export type UserProfilesInsert = z.infer<
  typeof generated.userProfilesInsertSchema
>;
export type UserProfilesUpdate = z.infer<
  typeof generated.userProfilesUpdateSchema
>;
export type UsersByOrganizationRow = z.infer<
  typeof generated.usersByOrganizationRowSchema
>;
export type UsersByOrganizationInsert = z.infer<
  typeof generated.usersByOrganizationInsertSchema
>;
export type UsersByOrganizationUpdate = z.infer<
  typeof generated.usersByOrganizationUpdateSchema
>;
export type UsersByOrganizationRelationships = z.infer<
  typeof generated.usersByOrganizationRelationshipsSchema
>;
export type AcceptInvitationArgs = z.infer<
  typeof generated.acceptInvitationArgsSchema
>;
export type AcceptInvitationReturns = z.infer<
  typeof generated.acceptInvitationReturnsSchema
>;
export type AddCreditsArgs = z.infer<typeof generated.addCreditsArgsSchema>;
export type AddCreditsReturns = z.infer<
  typeof generated.addCreditsReturnsSchema
>;
export type CanGrantPermissionArgs = z.infer<
  typeof generated.canGrantPermissionArgsSchema
>;
export type CanGrantPermissionReturns = z.infer<
  typeof generated.canGrantPermissionReturnsSchema
>;
export type CheckOrgAdminArgs = z.infer<
  typeof generated.checkOrgAdminArgsSchema
>;
export type CheckOrgAdminReturns = z.infer<
  typeof generated.checkOrgAdminReturnsSchema
>;
export type CheckOrgMembershipArgs = z.infer<
  typeof generated.checkOrgMembershipArgsSchema
>;
export type CheckOrgMembershipReturns = z.infer<
  typeof generated.checkOrgMembershipReturnsSchema
>;
export type CheckResourcePermissionArgs = z.infer<
  typeof generated.checkResourcePermissionArgsSchema
>;
export type CheckResourcePermissionReturns = z.infer<
  typeof generated.checkResourcePermissionReturnsSchema
>;
export type CleanupOrphanedInvitationsArgs = z.infer<
  typeof generated.cleanupOrphanedInvitationsArgsSchema
>;
export type CleanupOrphanedInvitationsReturns = z.infer<
  typeof generated.cleanupOrphanedInvitationsReturnsSchema
>;
export type DeductCreditsArgs = z.infer<
  typeof generated.deductCreditsArgsSchema
>;
export type DeductCreditsReturns = z.infer<
  typeof generated.deductCreditsReturnsSchema
>;
export type ExpireOldInvitationsArgs = z.infer<
  typeof generated.expireOldInvitationsArgsSchema
>;
export type ExpireOldInvitationsReturns = z.infer<
  typeof generated.expireOldInvitationsReturnsSchema
>;
export type GbtBitCompressArgs = z.infer<
  typeof generated.gbtBitCompressArgsSchema
>;
export type GbtBitCompressReturns = z.infer<
  typeof generated.gbtBitCompressReturnsSchema
>;
export type GbtBoolCompressArgs = z.infer<
  typeof generated.gbtBoolCompressArgsSchema
>;
export type GbtBoolCompressReturns = z.infer<
  typeof generated.gbtBoolCompressReturnsSchema
>;
export type GbtBoolFetchArgs = z.infer<typeof generated.gbtBoolFetchArgsSchema>;
export type GbtBoolFetchReturns = z.infer<
  typeof generated.gbtBoolFetchReturnsSchema
>;
export type GbtBpcharCompressArgs = z.infer<
  typeof generated.gbtBpcharCompressArgsSchema
>;
export type GbtBpcharCompressReturns = z.infer<
  typeof generated.gbtBpcharCompressReturnsSchema
>;
export type GbtByteaCompressArgs = z.infer<
  typeof generated.gbtByteaCompressArgsSchema
>;
export type GbtByteaCompressReturns = z.infer<
  typeof generated.gbtByteaCompressReturnsSchema
>;
export type GbtCashCompressArgs = z.infer<
  typeof generated.gbtCashCompressArgsSchema
>;
export type GbtCashCompressReturns = z.infer<
  typeof generated.gbtCashCompressReturnsSchema
>;
export type GbtCashFetchArgs = z.infer<typeof generated.gbtCashFetchArgsSchema>;
export type GbtCashFetchReturns = z.infer<
  typeof generated.gbtCashFetchReturnsSchema
>;
export type GbtDateCompressArgs = z.infer<
  typeof generated.gbtDateCompressArgsSchema
>;
export type GbtDateCompressReturns = z.infer<
  typeof generated.gbtDateCompressReturnsSchema
>;
export type GbtDateFetchArgs = z.infer<typeof generated.gbtDateFetchArgsSchema>;
export type GbtDateFetchReturns = z.infer<
  typeof generated.gbtDateFetchReturnsSchema
>;
export type GbtDecompressArgs = z.infer<
  typeof generated.gbtDecompressArgsSchema
>;
export type GbtDecompressReturns = z.infer<
  typeof generated.gbtDecompressReturnsSchema
>;
export type GbtEnumCompressArgs = z.infer<
  typeof generated.gbtEnumCompressArgsSchema
>;
export type GbtEnumCompressReturns = z.infer<
  typeof generated.gbtEnumCompressReturnsSchema
>;
export type GbtEnumFetchArgs = z.infer<typeof generated.gbtEnumFetchArgsSchema>;
export type GbtEnumFetchReturns = z.infer<
  typeof generated.gbtEnumFetchReturnsSchema
>;
export type GbtFloat4CompressArgs = z.infer<
  typeof generated.gbtFloat4CompressArgsSchema
>;
export type GbtFloat4CompressReturns = z.infer<
  typeof generated.gbtFloat4CompressReturnsSchema
>;
export type GbtFloat4FetchArgs = z.infer<
  typeof generated.gbtFloat4FetchArgsSchema
>;
export type GbtFloat4FetchReturns = z.infer<
  typeof generated.gbtFloat4FetchReturnsSchema
>;
export type GbtFloat8CompressArgs = z.infer<
  typeof generated.gbtFloat8CompressArgsSchema
>;
export type GbtFloat8CompressReturns = z.infer<
  typeof generated.gbtFloat8CompressReturnsSchema
>;
export type GbtFloat8FetchArgs = z.infer<
  typeof generated.gbtFloat8FetchArgsSchema
>;
export type GbtFloat8FetchReturns = z.infer<
  typeof generated.gbtFloat8FetchReturnsSchema
>;
export type GbtInetCompressArgs = z.infer<
  typeof generated.gbtInetCompressArgsSchema
>;
export type GbtInetCompressReturns = z.infer<
  typeof generated.gbtInetCompressReturnsSchema
>;
export type GbtInt2CompressArgs = z.infer<
  typeof generated.gbtInt2CompressArgsSchema
>;
export type GbtInt2CompressReturns = z.infer<
  typeof generated.gbtInt2CompressReturnsSchema
>;
export type GbtInt2FetchArgs = z.infer<typeof generated.gbtInt2FetchArgsSchema>;
export type GbtInt2FetchReturns = z.infer<
  typeof generated.gbtInt2FetchReturnsSchema
>;
export type GbtInt4CompressArgs = z.infer<
  typeof generated.gbtInt4CompressArgsSchema
>;
export type GbtInt4CompressReturns = z.infer<
  typeof generated.gbtInt4CompressReturnsSchema
>;
export type GbtInt4FetchArgs = z.infer<typeof generated.gbtInt4FetchArgsSchema>;
export type GbtInt4FetchReturns = z.infer<
  typeof generated.gbtInt4FetchReturnsSchema
>;
export type GbtInt8CompressArgs = z.infer<
  typeof generated.gbtInt8CompressArgsSchema
>;
export type GbtInt8CompressReturns = z.infer<
  typeof generated.gbtInt8CompressReturnsSchema
>;
export type GbtInt8FetchArgs = z.infer<typeof generated.gbtInt8FetchArgsSchema>;
export type GbtInt8FetchReturns = z.infer<
  typeof generated.gbtInt8FetchReturnsSchema
>;
export type GbtIntvCompressArgs = z.infer<
  typeof generated.gbtIntvCompressArgsSchema
>;
export type GbtIntvCompressReturns = z.infer<
  typeof generated.gbtIntvCompressReturnsSchema
>;
export type GbtIntvDecompressArgs = z.infer<
  typeof generated.gbtIntvDecompressArgsSchema
>;
export type GbtIntvDecompressReturns = z.infer<
  typeof generated.gbtIntvDecompressReturnsSchema
>;
export type GbtIntvFetchArgs = z.infer<typeof generated.gbtIntvFetchArgsSchema>;
export type GbtIntvFetchReturns = z.infer<
  typeof generated.gbtIntvFetchReturnsSchema
>;
export type GbtMacadCompressArgs = z.infer<
  typeof generated.gbtMacadCompressArgsSchema
>;
export type GbtMacadCompressReturns = z.infer<
  typeof generated.gbtMacadCompressReturnsSchema
>;
export type GbtMacadFetchArgs = z.infer<
  typeof generated.gbtMacadFetchArgsSchema
>;
export type GbtMacadFetchReturns = z.infer<
  typeof generated.gbtMacadFetchReturnsSchema
>;
export type GbtMacad8CompressArgs = z.infer<
  typeof generated.gbtMacad8CompressArgsSchema
>;
export type GbtMacad8CompressReturns = z.infer<
  typeof generated.gbtMacad8CompressReturnsSchema
>;
export type GbtMacad8FetchArgs = z.infer<
  typeof generated.gbtMacad8FetchArgsSchema
>;
export type GbtMacad8FetchReturns = z.infer<
  typeof generated.gbtMacad8FetchReturnsSchema
>;
export type GbtNumericCompressArgs = z.infer<
  typeof generated.gbtNumericCompressArgsSchema
>;
export type GbtNumericCompressReturns = z.infer<
  typeof generated.gbtNumericCompressReturnsSchema
>;
export type GbtOidCompressArgs = z.infer<
  typeof generated.gbtOidCompressArgsSchema
>;
export type GbtOidCompressReturns = z.infer<
  typeof generated.gbtOidCompressReturnsSchema
>;
export type GbtOidFetchArgs = z.infer<typeof generated.gbtOidFetchArgsSchema>;
export type GbtOidFetchReturns = z.infer<
  typeof generated.gbtOidFetchReturnsSchema
>;
export type GbtTextCompressArgs = z.infer<
  typeof generated.gbtTextCompressArgsSchema
>;
export type GbtTextCompressReturns = z.infer<
  typeof generated.gbtTextCompressReturnsSchema
>;
export type GbtTimeCompressArgs = z.infer<
  typeof generated.gbtTimeCompressArgsSchema
>;
export type GbtTimeCompressReturns = z.infer<
  typeof generated.gbtTimeCompressReturnsSchema
>;
export type GbtTimeFetchArgs = z.infer<typeof generated.gbtTimeFetchArgsSchema>;
export type GbtTimeFetchReturns = z.infer<
  typeof generated.gbtTimeFetchReturnsSchema
>;
export type GbtTimetzCompressArgs = z.infer<
  typeof generated.gbtTimetzCompressArgsSchema
>;
export type GbtTimetzCompressReturns = z.infer<
  typeof generated.gbtTimetzCompressReturnsSchema
>;
export type GbtTsCompressArgs = z.infer<
  typeof generated.gbtTsCompressArgsSchema
>;
export type GbtTsCompressReturns = z.infer<
  typeof generated.gbtTsCompressReturnsSchema
>;
export type GbtTsFetchArgs = z.infer<typeof generated.gbtTsFetchArgsSchema>;
export type GbtTsFetchReturns = z.infer<
  typeof generated.gbtTsFetchReturnsSchema
>;
export type GbtTstzCompressArgs = z.infer<
  typeof generated.gbtTstzCompressArgsSchema
>;
export type GbtTstzCompressReturns = z.infer<
  typeof generated.gbtTstzCompressReturnsSchema
>;
export type GbtUuidCompressArgs = z.infer<
  typeof generated.gbtUuidCompressArgsSchema
>;
export type GbtUuidCompressReturns = z.infer<
  typeof generated.gbtUuidCompressReturnsSchema
>;
export type GbtUuidFetchArgs = z.infer<typeof generated.gbtUuidFetchArgsSchema>;
export type GbtUuidFetchReturns = z.infer<
  typeof generated.gbtUuidFetchReturnsSchema
>;
export type GbtVarDecompressArgs = z.infer<
  typeof generated.gbtVarDecompressArgsSchema
>;
export type GbtVarDecompressReturns = z.infer<
  typeof generated.gbtVarDecompressReturnsSchema
>;
export type GbtVarFetchArgs = z.infer<typeof generated.gbtVarFetchArgsSchema>;
export type GbtVarFetchReturns = z.infer<
  typeof generated.gbtVarFetchReturnsSchema
>;
export type GbtreekeyVarInArgs = z.infer<
  typeof generated.gbtreekeyVarInArgsSchema
>;
export type GbtreekeyVarInReturns = z.infer<
  typeof generated.gbtreekeyVarInReturnsSchema
>;
export type GbtreekeyVarOutArgs = z.infer<
  typeof generated.gbtreekeyVarOutArgsSchema
>;
export type GbtreekeyVarOutReturns = z.infer<
  typeof generated.gbtreekeyVarOutReturnsSchema
>;
export type Gbtreekey16InArgs = z.infer<
  typeof generated.gbtreekey16InArgsSchema
>;
export type Gbtreekey16InReturns = z.infer<
  typeof generated.gbtreekey16InReturnsSchema
>;
export type Gbtreekey16OutArgs = z.infer<
  typeof generated.gbtreekey16OutArgsSchema
>;
export type Gbtreekey16OutReturns = z.infer<
  typeof generated.gbtreekey16OutReturnsSchema
>;
export type Gbtreekey2InArgs = z.infer<typeof generated.gbtreekey2InArgsSchema>;
export type Gbtreekey2InReturns = z.infer<
  typeof generated.gbtreekey2InReturnsSchema
>;
export type Gbtreekey2OutArgs = z.infer<
  typeof generated.gbtreekey2OutArgsSchema
>;
export type Gbtreekey2OutReturns = z.infer<
  typeof generated.gbtreekey2OutReturnsSchema
>;
export type Gbtreekey32InArgs = z.infer<
  typeof generated.gbtreekey32InArgsSchema
>;
export type Gbtreekey32InReturns = z.infer<
  typeof generated.gbtreekey32InReturnsSchema
>;
export type Gbtreekey32OutArgs = z.infer<
  typeof generated.gbtreekey32OutArgsSchema
>;
export type Gbtreekey32OutReturns = z.infer<
  typeof generated.gbtreekey32OutReturnsSchema
>;
export type Gbtreekey4InArgs = z.infer<typeof generated.gbtreekey4InArgsSchema>;
export type Gbtreekey4InReturns = z.infer<
  typeof generated.gbtreekey4InReturnsSchema
>;
export type Gbtreekey4OutArgs = z.infer<
  typeof generated.gbtreekey4OutArgsSchema
>;
export type Gbtreekey4OutReturns = z.infer<
  typeof generated.gbtreekey4OutReturnsSchema
>;
export type Gbtreekey8InArgs = z.infer<typeof generated.gbtreekey8InArgsSchema>;
export type Gbtreekey8InReturns = z.infer<
  typeof generated.gbtreekey8InReturnsSchema
>;
export type Gbtreekey8OutArgs = z.infer<
  typeof generated.gbtreekey8OutArgsSchema
>;
export type Gbtreekey8OutReturns = z.infer<
  typeof generated.gbtreekey8OutReturnsSchema
>;
export type GetOgImageInfoArgs = z.infer<
  typeof generated.getOgImageInfoArgsSchema
>;
export type GetOgImageInfoReturns = z.infer<
  typeof generated.getOgImageInfoReturnsSchema
>;
export type GetOrganizationCreditsArgs = z.infer<
  typeof generated.getOrganizationCreditsArgsSchema
>;
export type GetOrganizationCreditsReturns = z.infer<
  typeof generated.getOrganizationCreditsReturnsSchema
>;
export type GetUserCreditsArgs = z.infer<
  typeof generated.getUserCreditsArgsSchema
>;
export type GetUserCreditsReturns = z.infer<
  typeof generated.getUserCreditsReturnsSchema
>;
export type HasuraTokenHookArgs = z.infer<
  typeof generated.hasuraTokenHookArgsSchema
>;
export type HasuraTokenHookReturns = z.infer<
  typeof generated.hasuraTokenHookReturnsSchema
>;
export type PreviewDeductCreditsArgs = z.infer<
  typeof generated.previewDeductCreditsArgsSchema
>;
export type PreviewDeductCreditsReturns = z.infer<
  typeof generated.previewDeductCreditsReturnsSchema
>;
export type UuidOrNullArgs = z.infer<typeof generated.uuidOrNullArgsSchema>;
export type UuidOrNullReturns = z.infer<
  typeof generated.uuidOrNullReturnsSchema
>;
export type ValidateOwnershipLimitsArgs = z.infer<
  typeof generated.validateOwnershipLimitsArgsSchema
>;
export type ValidateOwnershipLimitsReturns = z.infer<
  typeof generated.validateOwnershipLimitsReturnsSchema
>;
export type ModelRevisionRow = z.infer<typeof generated.modelRevisionRowSchema>;
