/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "@/lib/types/supabase";

export const publicDatasetTypeSchema = z.enum([
  "USER_MODEL",
  "DATA_CONNECTOR",
  "DATA_INGESTION",
  "STATIC_MODEL",
]);

export const publicModelKindSchema = z.enum([
  "INCREMENTAL_BY_TIME_RANGE",
  "INCREMENTAL_BY_UNIQUE_KEY",
  "INCREMENTAL_BY_PARTITION",
  "SCD_TYPE_2_BY_TIME",
  "SCD_TYPE_2_BY_COLUMN",
  "FULL",
  "VIEW",
]);

export const publicRunStatusSchema = z.enum([
  "running",
  "completed",
  "failed",
  "canceled",
  "queued",
]);

export const publicRunTypeSchema = z.enum(["manual", "scheduled"]);

export const publicStepStatusSchema = z.enum([
  "running",
  "success",
  "failed",
  "canceled",
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAdminUsersRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.number(),
  name: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicAdminUsersInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicAdminUsersUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicAdminUsersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("admin_users_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicApiKeysRowSchema = z.object({
  api_key: z.string(),
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicApiKeysInsertSchema = z.object({
  api_key: z.string(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicApiKeysUpdateSchema = z.object({
  api_key: z.string().optional(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicApiKeysRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("api_keys_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("api_keys_user_id_fkey1"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicChatHistoryRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  data: z.string().nullable(),
  deleted_at: z.string().nullable(),
  display_name: z.string(),
  id: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicChatHistoryInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  display_name: z.string(),
  id: z.string().optional(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicChatHistoryUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  display_name: z.string().optional(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicChatHistoryRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("chat_history_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("chat_history_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicConnectorRelationshipsRowSchema = z.object({
  id: z.string(),
  org_id: z.string(),
  source_column_name: z.string(),
  source_table_id: z.string(),
  target_column_name: z.string().nullable(),
  target_oso_entity: z.string().nullable(),
  target_table_id: z.string().nullable(),
});

export const publicConnectorRelationshipsInsertSchema = z.object({
  id: z.string().optional(),
  org_id: z.string(),
  source_column_name: z.string(),
  source_table_id: z.string(),
  target_column_name: z.string().optional().nullable(),
  target_oso_entity: z.string().optional().nullable(),
  target_table_id: z.string().optional().nullable(),
});

export const publicConnectorRelationshipsUpdateSchema = z.object({
  id: z.string().optional(),
  org_id: z.string().optional(),
  source_column_name: z.string().optional(),
  source_table_id: z.string().optional(),
  target_column_name: z.string().optional().nullable(),
  target_oso_entity: z.string().optional().nullable(),
  target_table_id: z.string().optional().nullable(),
});

export const publicConnectorRelationshipsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_org_id"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_source_column"),
    columns: z.tuple([
      z.literal("source_table_id"),
      z.literal("source_column_name"),
    ]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_column_contexts"),
    referencedColumns: z.tuple([
      z.literal("table_id"),
      z.literal("column_name"),
    ]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_source_table"),
    columns: z.tuple([z.literal("source_table_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_table_contexts"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_target_column"),
    columns: z.tuple([
      z.literal("target_table_id"),
      z.literal("target_column_name"),
    ]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_column_contexts"),
    referencedColumns: z.tuple([
      z.literal("table_id"),
      z.literal("column_name"),
    ]),
  }),
  z.object({
    foreignKeyName: z.literal("fk_target_table"),
    columns: z.tuple([z.literal("target_table_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_table_contexts"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDatasetsRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  dataset_type: publicDatasetTypeSchema,
  deleted_at: z.string().nullable(),
  description: z.string().nullable(),
  display_name: z.string(),
  id: z.string(),
  is_public: z.boolean(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicDatasetsInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  dataset_type: publicDatasetTypeSchema,
  deleted_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  display_name: z.string(),
  id: z.string().optional(),
  is_public: z.boolean().optional(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicDatasetsUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  dataset_type: publicDatasetTypeSchema.optional(),
  deleted_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  display_name: z.string().optional(),
  id: z.string().optional(),
  is_public: z.boolean().optional(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicDatasetsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("datasets_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("datasets_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDatasetsByOrganizationRowSchema = z.object({
  created_at: z.string(),
  dataset_id: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  org_id: z.string(),
});

export const publicDatasetsByOrganizationInsertSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string(),
});

export const publicDatasetsByOrganizationUpdateSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string().optional(),
});

export const publicDatasetsByOrganizationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("datasets_by_organization_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("datasets_by_organization_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDynamicColumnContextsRowSchema = z.object({
  column_name: z.string(),
  data_type: z.string(),
  description: z.string().nullable(),
  sample_data: z.string().nullable(),
  table_id: z.string(),
});

export const publicDynamicColumnContextsInsertSchema = z.object({
  column_name: z.string(),
  data_type: z.string(),
  description: z.string().optional().nullable(),
  sample_data: z.string().optional().nullable(),
  table_id: z.string(),
});

export const publicDynamicColumnContextsUpdateSchema = z.object({
  column_name: z.string().optional(),
  data_type: z.string().optional(),
  description: z.string().optional().nullable(),
  sample_data: z.string().optional().nullable(),
  table_id: z.string().optional(),
});

export const publicDynamicColumnContextsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_table_context"),
    columns: z.tuple([z.literal("table_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_table_contexts"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDynamicConnectorsRowSchema = z.object({
  config: jsonSchema.nullable(),
  connector_name: z.string(),
  connector_type: z.string(),
  created_at: z.string(),
  created_by: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  is_public: z.boolean().nullable(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicDynamicConnectorsInsertSchema = z.object({
  config: jsonSchema.optional().nullable(),
  connector_name: z.string(),
  connector_type: z.string(),
  created_at: z.string().optional(),
  created_by: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional().nullable(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicDynamicConnectorsUpdateSchema = z.object({
  config: jsonSchema.optional().nullable(),
  connector_name: z.string().optional(),
  connector_type: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional().nullable(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicDynamicConnectorsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_org_id"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDynamicReplicationsRowSchema = z.object({
  config: jsonSchema,
  created_at: z.string(),
  created_by: z.string(),
  credentials_path: z.string().nullable(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  org_id: z.string(),
  replication_name: z.string(),
  replication_type: z.string(),
  updated_at: z.string(),
});

export const publicDynamicReplicationsInsertSchema = z.object({
  config: jsonSchema,
  created_at: z.string().optional(),
  created_by: z.string(),
  credentials_path: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string(),
  replication_name: z.string(),
  replication_type: z.string(),
  updated_at: z.string().optional(),
});

export const publicDynamicReplicationsUpdateSchema = z.object({
  config: jsonSchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credentials_path: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  replication_name: z.string().optional(),
  replication_type: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicDynamicReplicationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_org_id"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDynamicTableContextsRowSchema = z.object({
  connector_id: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  table_name: z.string(),
});

export const publicDynamicTableContextsInsertSchema = z.object({
  connector_id: z.string(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  table_name: z.string(),
});

export const publicDynamicTableContextsUpdateSchema = z.object({
  connector_id: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  table_name: z.string().optional(),
});

export const publicDynamicTableContextsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_connector_id"),
    columns: z.tuple([z.literal("connector_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("dynamic_connectors"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicInvitationsRowSchema = z.object({
  accepted_at: z.string().nullable(),
  accepted_by: z.string().nullable(),
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  email: z.string(),
  expires_at: z.string(),
  id: z.string(),
  invited_by: z.string(),
  org_id: z.string(),
  org_name: z.string(),
  updated_at: z.string(),
});

export const publicInvitationsInsertSchema = z.object({
  accepted_at: z.string().optional().nullable(),
  accepted_by: z.string().optional().nullable(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  email: z.string(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  invited_by: z.string(),
  org_id: z.string(),
  org_name: z.string(),
  updated_at: z.string().optional(),
});

export const publicInvitationsUpdateSchema = z.object({
  accepted_at: z.string().optional().nullable(),
  accepted_by: z.string().optional().nullable(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  email: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  invited_by: z.string().optional(),
  org_id: z.string().optional(),
  org_name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicInvitationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("invitations_accepted_by_fkey"),
    columns: z.tuple([z.literal("accepted_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("invitations_invited_by_fkey"),
    columns: z.tuple([z.literal("invited_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("invitations_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicModelColumnTypeSchema = z.object({
  name: z.string().nullable(),
  type: z.string().nullable(),
  description: z.string().nullable(),
});

export const publicMaterializationInsertSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string(),
  id: z.string().optional(),
  org_id: z.string(),
  run_id: z.string(),
  schema: z.array(publicModelColumnTypeSchema),
  step_id: z.string().optional().nullable(),
  table_id: z.string(),
  warehouse_fqn: z.string(),
});

export const publicMaterializationUpdateSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string().optional(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  run_id: z.string().optional(),
  schema: z.array(publicModelColumnTypeSchema).optional(),
  step_id: z.string().optional().nullable(),
  table_id: z.string().optional(),
  warehouse_fqn: z.string().optional(),
});

export const publicMaterializationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("fk_step"),
    columns: z.tuple([z.literal("step_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("step"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("materialization_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("materialization_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("materialization_run_id_fkey"),
    columns: z.tuple([z.literal("run_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("run"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicModelRowSchema = z.object({
  created_at: z.string(),
  dataset_id: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  is_enabled: z.boolean(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicModelInsertSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_enabled: z.boolean().optional(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicModelUpdateSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_enabled: z.boolean().optional(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicModelRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("model_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("model_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicModelReleaseRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  model_id: z.string(),
  model_revision_id: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicModelReleaseInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  model_id: z.string(),
  model_revision_id: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicModelReleaseUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  model_id: z.string().optional(),
  model_revision_id: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicModelReleaseRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("model_release_model_id_fkey"),
    columns: z.tuple([z.literal("model_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("model"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("model_release_model_revision_id_fkey"),
    columns: z.tuple([z.literal("model_revision_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("model_revision"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("model_release_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicModelDependencyTypeSchema = z.object({
  model_id: z.string().nullable(),
  alias: z.string().nullable(),
});

export const publicModelKindOptionsSchema = z.object({
  time_column: z.string().nullable(),
  time_column_format: z.string().nullable(),
  batch_size: z.number().nullable(),
  lookback: z.number().nullable(),
  unique_key_columns: z.array(z.string()).nullable(),
  when_matched_sql: z.string().nullable(),
  merge_filter: z.string().nullable(),
  valid_from_name: z.string().nullable(),
  valid_to_name: z.string().nullable(),
  invalidate_hard_deletes: z.boolean().nullable(),
  updated_at_column: z.string().nullable(),
  updated_at_as_valid_from: z.boolean().nullable(),
  scd_columns: z.array(z.string()).nullable(),
  execution_time_as_valid_from: z.boolean().nullable(),
});

export const publicModelRevisionInsertSchema = z.object({
  clustered_by: z.array(z.string()).optional().nullable(),
  code: z.string(),
  created_at: z.string().optional(),
  cron: z.string(),
  depends_on: z.array(publicModelDependencyTypeSchema).optional().nullable(),
  description: z.string().optional().nullable(),
  end: z.string().optional().nullable(),
  hash: z.string(),
  id: z.string().optional(),
  kind: publicModelKindSchema,
  kind_options: publicModelKindOptionsSchema.optional().nullable(),
  language: z.string(),
  model_id: z.string(),
  name: z.string(),
  org_id: z.string(),
  partitioned_by: z.array(z.string()).optional().nullable(),
  revision_number: z.number(),
  schema: z.array(publicModelColumnTypeSchema),
  start: z.string().optional().nullable(),
});

export const publicModelRevisionUpdateSchema = z.object({
  clustered_by: z.array(z.string()).optional().nullable(),
  code: z.string().optional(),
  created_at: z.string().optional(),
  cron: z.string().optional(),
  depends_on: z.array(publicModelDependencyTypeSchema).optional().nullable(),
  description: z.string().optional().nullable(),
  end: z.string().optional().nullable(),
  hash: z.string().optional(),
  id: z.string().optional(),
  kind: publicModelKindSchema.optional(),
  kind_options: publicModelKindOptionsSchema.optional().nullable(),
  language: z.string().optional(),
  model_id: z.string().optional(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  partitioned_by: z.array(z.string()).optional().nullable(),
  revision_number: z.number().optional(),
  schema: z.array(publicModelColumnTypeSchema).optional(),
  start: z.string().optional().nullable(),
});

export const publicModelRevisionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("model_revision_model_id_fkey"),
    columns: z.tuple([z.literal("model_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("model"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("model_revision_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicNotebooksRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string(),
  data: z.string().nullable(),
  deleted_at: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  notebook_name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicNotebooksInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicNotebooksUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  data: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicNotebooksRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("saved_queries_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("saved_queries_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOrganizationCreditTransactionsRowSchema = z.object({
  amount: z.number(),
  api_endpoint: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  org_id: z.string(),
  transaction_type: z.string(),
  user_id: z.string(),
});

export const publicOrganizationCreditTransactionsInsertSchema = z.object({
  amount: z.number(),
  api_endpoint: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string(),
  transaction_type: z.string(),
  user_id: z.string(),
});

export const publicOrganizationCreditTransactionsUpdateSchema = z.object({
  amount: z.number().optional(),
  api_endpoint: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string().optional(),
  transaction_type: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicOrganizationCreditTransactionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organization_credit_transactions_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOrganizationCreditsRowSchema = z.object({
  created_at: z.string(),
  credits_balance: z.number(),
  id: z.string(),
  last_refill_at: z.string().nullable(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicOrganizationCreditsInsertSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  last_refill_at: z.string().optional().nullable(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicOrganizationCreditsUpdateSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  last_refill_at: z.string().optional().nullable(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicOrganizationCreditsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organization_credits_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOrganizationsRowSchema = z.object({
  billing_contact_email: z.string().nullable(),
  created_at: z.string(),
  created_by: z.string(),
  deleted_at: z.string().nullable(),
  enterprise_support_url: z.string().nullable(),
  id: z.string(),
  org_name: z.string(),
  plan_id: z.string(),
  updated_at: z.string(),
});

export const publicOrganizationsInsertSchema = z.object({
  billing_contact_email: z.string().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string(),
  deleted_at: z.string().optional().nullable(),
  enterprise_support_url: z.string().optional().nullable(),
  id: z.string().optional(),
  org_name: z.string(),
  plan_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicOrganizationsUpdateSchema = z.object({
  billing_contact_email: z.string().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  enterprise_support_url: z.string().optional().nullable(),
  id: z.string().optional(),
  org_name: z.string().optional(),
  plan_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicOrganizationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("organizations_created_by_fkey1"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("organizations_plan_id_fkey"),
    columns: z.tuple([z.literal("plan_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("pricing_plan"),
    referencedColumns: z.tuple([z.literal("plan_id")]),
  }),
]);

export const publicPricingPlanRowSchema = z.object({
  created_at: z.string(),
  max_credits_per_cycle: z.number().nullable(),
  plan_id: z.string(),
  plan_name: z.string(),
  price_per_credit: z.number(),
  priority: z.number(),
  refill_cycle_days: z.number().nullable(),
  updated_at: z.string(),
});

export const publicPricingPlanInsertSchema = z.object({
  created_at: z.string().optional(),
  max_credits_per_cycle: z.number().optional().nullable(),
  plan_id: z.string().optional(),
  plan_name: z.string(),
  price_per_credit: z.number(),
  priority: z.number().optional(),
  refill_cycle_days: z.number().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicPricingPlanUpdateSchema = z.object({
  created_at: z.string().optional(),
  max_credits_per_cycle: z.number().optional().nullable(),
  plan_id: z.string().optional(),
  plan_name: z.string().optional(),
  price_per_credit: z.number().optional(),
  priority: z.number().optional(),
  refill_cycle_days: z.number().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicPublishedNotebooksRowSchema = z.object({
  created_at: z.string(),
  data_path: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  notebook_id: z.string(),
  updated_at: z.string(),
  updated_by: z.string().nullable(),
});

export const publicPublishedNotebooksInsertSchema = z.object({
  created_at: z.string().optional(),
  data_path: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_id: z.string(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional().nullable(),
});

export const publicPublishedNotebooksUpdateSchema = z.object({
  created_at: z.string().optional(),
  data_path: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional().nullable(),
});

export const publicPublishedNotebooksRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("published_notebooks_notebook_id_fkey"),
    columns: z.tuple([z.literal("notebook_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("notebooks"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicPurchaseIntentsRowSchema = z.object({
  completed_at: z.string().nullable(),
  created_at: z.string(),
  credits_amount: z.number(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  org_id: z.string().nullable(),
  package_id: z.string(),
  price_cents: z.number(),
  status: z.string(),
  stripe_session_id: z.string(),
  user_id: z.string(),
});

export const publicPurchaseIntentsInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  credits_amount: z.number(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string().optional().nullable(),
  package_id: z.string(),
  price_cents: z.number(),
  status: z.string().optional(),
  stripe_session_id: z.string(),
  user_id: z.string(),
});

export const publicPurchaseIntentsUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  credits_amount: z.number().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  org_id: z.string().optional().nullable(),
  package_id: z.string().optional(),
  price_cents: z.number().optional(),
  status: z.string().optional(),
  stripe_session_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicPurchaseIntentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("purchase_intents_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicReservedNamesRowSchema = z.object({
  created_at: z.string(),
  name: z.string(),
});

export const publicReservedNamesInsertSchema = z.object({
  created_at: z.string().optional(),
  name: z.string(),
});

export const publicReservedNamesUpdateSchema = z.object({
  created_at: z.string().optional(),
  name: z.string().optional(),
});

export const publicResourcePermissionsRowSchema = z.object({
  chat_id: z.string().nullable(),
  created_at: z.string(),
  granted_by: z.string().nullable(),
  id: z.string(),
  notebook_id: z.string().nullable(),
  permission_level: z.string(),
  revoked_at: z.string().nullable(),
  updated_at: z.string(),
  user_id: z.string().nullable(),
});

export const publicResourcePermissionsInsertSchema = z.object({
  chat_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  granted_by: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_id: z.string().optional().nullable(),
  permission_level: z.string(),
  revoked_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicResourcePermissionsUpdateSchema = z.object({
  chat_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  granted_by: z.string().optional().nullable(),
  id: z.string().optional(),
  notebook_id: z.string().optional().nullable(),
  permission_level: z.string().optional(),
  revoked_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicResourcePermissionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("resource_permissions_chat_id_fkey"),
    columns: z.tuple([z.literal("chat_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("chat_history"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("resource_permissions_granted_by_fkey"),
    columns: z.tuple([z.literal("granted_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("resource_permissions_notebook_id_fkey"),
    columns: z.tuple([z.literal("notebook_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("notebooks"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("resource_permissions_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicRunRowSchema = z.object({
  completed_at: z.string().nullable(),
  dataset_id: z.string().nullable(),
  id: z.string(),
  logs_url: z.string().nullable(),
  org_id: z.string(),
  queued_at: z.string(),
  requested_by: z.string().nullable(),
  run_type: publicRunTypeSchema,
  started_at: z.string().nullable(),
  status: publicRunStatusSchema,
  ttl: z.string().nullable(),
});

export const publicRunInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  dataset_id: z.string().optional().nullable(),
  id: z.string().optional(),
  logs_url: z.string().optional().nullable(),
  org_id: z.string(),
  queued_at: z.string().optional(),
  requested_by: z.string().optional().nullable(),
  run_type: publicRunTypeSchema.optional(),
  started_at: z.string().optional().nullable(),
  status: publicRunStatusSchema.optional(),
  ttl: z.string().optional().nullable(),
});

export const publicRunUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  dataset_id: z.string().optional().nullable(),
  id: z.string().optional(),
  logs_url: z.string().optional().nullable(),
  org_id: z.string().optional(),
  queued_at: z.string().optional(),
  requested_by: z.string().optional().nullable(),
  run_type: publicRunTypeSchema.optional(),
  started_at: z.string().optional().nullable(),
  status: publicRunStatusSchema.optional(),
  ttl: z.string().optional().nullable(),
});

export const publicRunRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("run_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("run_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicStaticModelRowSchema = z.object({
  created_at: z.string(),
  dataset_id: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
});

export const publicStaticModelInsertSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  org_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicStaticModelUpdateSchema = z.object({
  created_at: z.string().optional(),
  dataset_id: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicStaticModelRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("static_model_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("static_model_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicStepRowSchema = z.object({
  completed_at: z.string().nullable(),
  display_name: z.string(),
  id: z.string(),
  logs_url: z.string().nullable(),
  name: z.string(),
  org_id: z.string(),
  run_id: z.string(),
  started_at: z.string(),
  status: publicStepStatusSchema,
});

export const publicStepInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  display_name: z.string(),
  id: z.string().optional(),
  logs_url: z.string().optional().nullable(),
  name: z.string(),
  org_id: z.string(),
  run_id: z.string(),
  started_at: z.string().optional(),
  status: publicStepStatusSchema.optional(),
});

export const publicStepUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  display_name: z.string().optional(),
  id: z.string().optional(),
  logs_url: z.string().optional().nullable(),
  name: z.string().optional(),
  org_id: z.string().optional(),
  run_id: z.string().optional(),
  started_at: z.string().optional(),
  status: publicStepStatusSchema.optional(),
});

export const publicStepRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("step_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("step_run_id_fkey"),
    columns: z.tuple([z.literal("run_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("run"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserCreditsRowSchema = z.object({
  created_at: z.string(),
  credits_balance: z.number(),
  id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicUserCreditsInsertSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicUserCreditsUpdateSchema = z.object({
  created_at: z.string().optional(),
  credits_balance: z.number().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  email: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  updated_at: z.string().nullable(),
  website: z.string().nullable(),
});

export const publicUserProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string(),
  updated_at: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const publicUserProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const publicUsersByOrganizationRowSchema = z.object({
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  org_id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
  user_role: z.string(),
});

export const publicUsersByOrganizationInsertSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
  user_role: z.string(),
});

export const publicUsersByOrganizationUpdateSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  id: z.string().optional(),
  org_id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  user_role: z.string().optional(),
});

export const publicUsersByOrganizationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("users_by_organization_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("users_by_organization_user_id_fkey1"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicModelAsTableRowSchema = z.object({
  dataset_id: z.string().nullable(),
  org_id: z.string().nullable(),
  table_id: z.string().nullable(),
  table_name: z.string().nullable(),
});

export const publicModelAsTableRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("model_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("model_release_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTableLookupRowSchema = z.object({
  dataset_id: z.string().nullable(),
  logical_fqn: z.string().nullable(),
  org_id: z.string().nullable(),
  table_id: z.string().nullable(),
  table_name: z.string().nullable(),
  warehouse_fqn: z.string().nullable(),
});

export const publicTableLookupRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("model_dataset_id_fkey"),
    columns: z.tuple([z.literal("dataset_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("datasets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("model_release_org_id_fkey"),
    columns: z.tuple([z.literal("org_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organizations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicAcceptInvitationArgsSchema = z.object({
  p_invitation_id: z.string(),
  p_user_id: z.string(),
});

export const publicAcceptInvitationReturnsSchema = z.boolean();

export const publicAddCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_metadata: jsonSchema.optional(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const publicAddCreditsReturnsSchema = z.boolean();

export const publicCanGrantPermissionArgsSchema = z.object({
  granter_id: z.string(),
  permission_to_grant: z.string(),
  target_resource_id: z.string(),
  target_resource_type: z.string(),
  target_user_id: z.string().optional(),
});

export const publicCanGrantPermissionReturnsSchema = z.boolean();

export const publicCheckOrgAdminArgsSchema = z.object({
  check_org_id: z.string(),
  check_user_id: z.string(),
});

export const publicCheckOrgAdminReturnsSchema = z.boolean();

export const publicCheckOrgMembershipArgsSchema = z.object({
  check_org_id: z.string(),
  check_user_id: z.string(),
});

export const publicCheckOrgMembershipReturnsSchema = z.boolean();

export const publicCheckResourcePermissionArgsSchema = z.object({
  p_resource_id: z.string(),
  p_resource_type: z.string(),
});

export const publicCheckResourcePermissionReturnsSchema = jsonSchema;

export const publicCleanupOrphanedInvitationsArgsSchema = z.never();

export const publicCleanupOrphanedInvitationsReturnsSchema = z.undefined();

export const publicDeductCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_api_endpoint: z.string().optional(),
  p_metadata: jsonSchema.optional(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const publicDeductCreditsReturnsSchema = z.boolean();

export const publicExpireOldInvitationsArgsSchema = z.never();

export const publicExpireOldInvitationsReturnsSchema = z.undefined();

export const publicGetOgImageInfoArgsSchema = z.object({
  p_notebook_name: z.string(),
  p_org_name: z.string(),
});

export const publicGetOgImageInfoReturnsSchema = jsonSchema;

export const publicGetOrganizationCreditsArgsSchema = z.object({
  p_org_id: z.string(),
});

export const publicGetOrganizationCreditsReturnsSchema = z.number();

export const publicGetUserCreditsArgsSchema = z.object({
  p_user_id: z.string(),
});

export const publicGetUserCreditsReturnsSchema = z.number();

export const publicHasuraTokenHookArgsSchema = z.object({
  event: jsonSchema,
});

export const publicHasuraTokenHookReturnsSchema = jsonSchema;

export const publicPreviewDeductCreditsArgsSchema = z.object({
  p_amount: z.number(),
  p_api_endpoint: z.string().optional(),
  p_metadata: jsonSchema.optional(),
  p_transaction_type: z.string(),
  p_user_id: z.string(),
});

export const publicPreviewDeductCreditsReturnsSchema = z.boolean();

export const publicUuidOrNullArgsSchema = z.object({
  str: z.string(),
});

export const publicUuidOrNullReturnsSchema = z.string();

export const publicValidateOwnershipLimitsArgsSchema = z.object({
  p_current_record_id: z.string().optional(),
  p_new_role: z.string(),
  p_old_role: z.string().optional(),
  p_user_id: z.string(),
});

export const publicValidateOwnershipLimitsReturnsSchema = z.boolean();

export const publicMaterializationRowSchema = z.object({
  created_at: z.string(),
  dataset_id: z.string(),
  id: z.string(),
  org_id: z.string(),
  run_id: z.string(),
  schema: z.array(publicModelColumnTypeSchema),
  step_id: z.string().nullable(),
  table_id: z.string(),
  warehouse_fqn: z.string(),
});

export const publicModelRevisionRowSchema = z.object({
  clustered_by: z.array(z.string()).nullable(),
  code: z.string(),
  created_at: z.string(),
  cron: z.string(),
  depends_on: z.array(publicModelDependencyTypeSchema).nullable(),
  description: z.string().nullable(),
  end: z.string().nullable(),
  hash: z.string(),
  id: z.string(),
  kind: publicModelKindSchema,
  kind_options: publicModelKindOptionsSchema.nullable(),
  language: z.string(),
  model_id: z.string(),
  name: z.string(),
  org_id: z.string(),
  partitioned_by: z.array(z.string()).nullable(),
  revision_number: z.number(),
  schema: z.array(publicModelColumnTypeSchema),
  start: z.string().nullable(),
});
