/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "@/lib/types/schema";
export type Json = z.infer<typeof generated.jsonSchema>;
export type AdminUsersRow = z.infer<typeof generated.adminUsersRowSchema>;
export type AdminUsersInsert = z.infer<typeof generated.adminUsersInsertSchema>;
export type AdminUsersUpdate = z.infer<typeof generated.adminUsersUpdateSchema>;
export type AdminUsersRelationships = z.infer<
  typeof generated.adminUsersRelationshipsSchema
>;
export type ApiKeysRow = z.infer<typeof generated.apiKeysRowSchema>;
export type ApiKeysInsert = z.infer<typeof generated.apiKeysInsertSchema>;
export type ApiKeysUpdate = z.infer<typeof generated.apiKeysUpdateSchema>;
export type ApiKeysRelationships = z.infer<
  typeof generated.apiKeysRelationshipsSchema
>;
export type ChatHistoryRow = z.infer<typeof generated.chatHistoryRowSchema>;
export type ChatHistoryInsert = z.infer<
  typeof generated.chatHistoryInsertSchema
>;
export type ChatHistoryUpdate = z.infer<
  typeof generated.chatHistoryUpdateSchema
>;
export type ChatHistoryRelationships = z.infer<
  typeof generated.chatHistoryRelationshipsSchema
>;
export type ConnectorRelationshipsRow = z.infer<
  typeof generated.connectorRelationshipsRowSchema
>;
export type ConnectorRelationshipsInsert = z.infer<
  typeof generated.connectorRelationshipsInsertSchema
>;
export type ConnectorRelationshipsUpdate = z.infer<
  typeof generated.connectorRelationshipsUpdateSchema
>;
export type ConnectorRelationshipsRelationships = z.infer<
  typeof generated.connectorRelationshipsRelationshipsSchema
>;
export type CreditTransactionsRow = z.infer<
  typeof generated.creditTransactionsRowSchema
>;
export type CreditTransactionsInsert = z.infer<
  typeof generated.creditTransactionsInsertSchema
>;
export type CreditTransactionsUpdate = z.infer<
  typeof generated.creditTransactionsUpdateSchema
>;
export type DynamicColumnContextsRow = z.infer<
  typeof generated.dynamicColumnContextsRowSchema
>;
export type DynamicColumnContextsInsert = z.infer<
  typeof generated.dynamicColumnContextsInsertSchema
>;
export type DynamicColumnContextsUpdate = z.infer<
  typeof generated.dynamicColumnContextsUpdateSchema
>;
export type DynamicColumnContextsRelationships = z.infer<
  typeof generated.dynamicColumnContextsRelationshipsSchema
>;
export type DynamicConnectorsRow = z.infer<
  typeof generated.dynamicConnectorsRowSchema
>;
export type DynamicConnectorsInsert = z.infer<
  typeof generated.dynamicConnectorsInsertSchema
>;
export type DynamicConnectorsUpdate = z.infer<
  typeof generated.dynamicConnectorsUpdateSchema
>;
export type DynamicConnectorsRelationships = z.infer<
  typeof generated.dynamicConnectorsRelationshipsSchema
>;
export type DynamicTableContextsRow = z.infer<
  typeof generated.dynamicTableContextsRowSchema
>;
export type DynamicTableContextsInsert = z.infer<
  typeof generated.dynamicTableContextsInsertSchema
>;
export type DynamicTableContextsUpdate = z.infer<
  typeof generated.dynamicTableContextsUpdateSchema
>;
export type DynamicTableContextsRelationships = z.infer<
  typeof generated.dynamicTableContextsRelationshipsSchema
>;
export type OrganizationCreditTransactionsRow = z.infer<
  typeof generated.organizationCreditTransactionsRowSchema
>;
export type OrganizationCreditTransactionsInsert = z.infer<
  typeof generated.organizationCreditTransactionsInsertSchema
>;
export type OrganizationCreditTransactionsUpdate = z.infer<
  typeof generated.organizationCreditTransactionsUpdateSchema
>;
export type OrganizationCreditTransactionsRelationships = z.infer<
  typeof generated.organizationCreditTransactionsRelationshipsSchema
>;
export type OrganizationCreditsRow = z.infer<
  typeof generated.organizationCreditsRowSchema
>;
export type OrganizationCreditsInsert = z.infer<
  typeof generated.organizationCreditsInsertSchema
>;
export type OrganizationCreditsUpdate = z.infer<
  typeof generated.organizationCreditsUpdateSchema
>;
export type OrganizationCreditsRelationships = z.infer<
  typeof generated.organizationCreditsRelationshipsSchema
>;
export type OrganizationsRow = z.infer<typeof generated.organizationsRowSchema>;
export type OrganizationsInsert = z.infer<
  typeof generated.organizationsInsertSchema
>;
export type OrganizationsUpdate = z.infer<
  typeof generated.organizationsUpdateSchema
>;
export type OrganizationsRelationships = z.infer<
  typeof generated.organizationsRelationshipsSchema
>;
export type PurchaseIntentsRow = z.infer<
  typeof generated.purchaseIntentsRowSchema
>;
export type PurchaseIntentsInsert = z.infer<
  typeof generated.purchaseIntentsInsertSchema
>;
export type PurchaseIntentsUpdate = z.infer<
  typeof generated.purchaseIntentsUpdateSchema
>;
export type PurchaseIntentsRelationships = z.infer<
  typeof generated.purchaseIntentsRelationshipsSchema
>;
export type SavedQueriesRow = z.infer<typeof generated.savedQueriesRowSchema>;
export type SavedQueriesInsert = z.infer<
  typeof generated.savedQueriesInsertSchema
>;
export type SavedQueriesUpdate = z.infer<
  typeof generated.savedQueriesUpdateSchema
>;
export type SavedQueriesRelationships = z.infer<
  typeof generated.savedQueriesRelationshipsSchema
>;
export type UserCreditsRow = z.infer<typeof generated.userCreditsRowSchema>;
export type UserCreditsInsert = z.infer<
  typeof generated.userCreditsInsertSchema
>;
export type UserCreditsUpdate = z.infer<
  typeof generated.userCreditsUpdateSchema
>;
export type UserProfilesRow = z.infer<typeof generated.userProfilesRowSchema>;
export type UserProfilesInsert = z.infer<
  typeof generated.userProfilesInsertSchema
>;
export type UserProfilesUpdate = z.infer<
  typeof generated.userProfilesUpdateSchema
>;
export type UsersByOrganizationRow = z.infer<
  typeof generated.usersByOrganizationRowSchema
>;
export type UsersByOrganizationInsert = z.infer<
  typeof generated.usersByOrganizationInsertSchema
>;
export type UsersByOrganizationUpdate = z.infer<
  typeof generated.usersByOrganizationUpdateSchema
>;
export type UsersByOrganizationRelationships = z.infer<
  typeof generated.usersByOrganizationRelationshipsSchema
>;
export type AddCreditsArgs = z.infer<typeof generated.addCreditsArgsSchema>;
export type AddCreditsReturns = z.infer<
  typeof generated.addCreditsReturnsSchema
>;
export type AddOrganizationCreditsArgs = z.infer<
  typeof generated.addOrganizationCreditsArgsSchema
>;
export type AddOrganizationCreditsReturns = z.infer<
  typeof generated.addOrganizationCreditsReturnsSchema
>;
export type DeductCreditsArgs = z.infer<
  typeof generated.deductCreditsArgsSchema
>;
export type DeductCreditsReturns = z.infer<
  typeof generated.deductCreditsReturnsSchema
>;
export type DeductOrganizationCreditsArgs = z.infer<
  typeof generated.deductOrganizationCreditsArgsSchema
>;
export type DeductOrganizationCreditsReturns = z.infer<
  typeof generated.deductOrganizationCreditsReturnsSchema
>;
export type GetOrganizationCreditsArgs = z.infer<
  typeof generated.getOrganizationCreditsArgsSchema
>;
export type GetOrganizationCreditsReturns = z.infer<
  typeof generated.getOrganizationCreditsReturnsSchema
>;
export type GetUserCreditsArgs = z.infer<
  typeof generated.getUserCreditsArgsSchema
>;
export type GetUserCreditsReturns = z.infer<
  typeof generated.getUserCreditsReturnsSchema
>;
export type HasuraTokenHookArgs = z.infer<
  typeof generated.hasuraTokenHookArgsSchema
>;
export type HasuraTokenHookReturns = z.infer<
  typeof generated.hasuraTokenHookReturnsSchema
>;
export type PreviewDeductCreditsArgs = z.infer<
  typeof generated.previewDeductCreditsArgsSchema
>;
export type PreviewDeductCreditsReturns = z.infer<
  typeof generated.previewDeductCreditsReturnsSchema
>;
export type PreviewDeductOrganizationCreditsArgs = z.infer<
  typeof generated.previewDeductOrganizationCreditsArgsSchema
>;
export type PreviewDeductOrganizationCreditsReturns = z.infer<
  typeof generated.previewDeductOrganizationCreditsReturnsSchema
>;
