---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-secrets-init
  labels:
    toolkit.fluxcd.io/tenant: ops
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: skm
  namespace: kube-secrets-init
spec:
  interval: 24h
  url: https://charts.sagikazarmark.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-secrets-init
  namespace: kube-secrets-init
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-secrets-init
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: skm
        namespace: kube-secrets-init
      interval: 1h
  values:
    certificate:
      useCertManager: true
    generate: false
    provider: google
    namespaceSelector:
      matchLabels:
        kube-secrets-init.doit-intl.com/enable-mutation: "true"