apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common/cert-manager.yaml
- ./secrets-store-csi-driver
- ./gcp-secrets-store-plugin
- kube-secrets-init.yaml
- ingress-internal-cloudflare.yaml
- cloudsql-proxy-operator.yaml
- keda.yaml
