apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-nessie
spec:
  values:
    catalog:
      enabled: true
      iceberg:
        defaultWarehouse: warehouse
        warehouses:
          - name: warehouse
            location: s3://local-storage/
      storage:
        s3:
          defaultOptions:
            accessKeySecret:
              awsAccessKeyId: accessKey
              awsSecretAccessKey: secretKey
              name: nessie-minio
            endpoint: https://minio.local-minio.svc.cluster.local
            pathStyleAccess: true
            region: local
    jdbc:
      jdbcUrl: jdbc:postgresql://nessie-psql-postgresql.local-nessie-psql.svc.cluster.local:5432/postgres
      secret:
        name: nessie-postgres
        password: password
        username: username
    versionStoreType: JDBC

