apiVersion: v1
kind: Namespace
metadata:
  name: base-mcs
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcs
  namespace: base-mcs
spec:
  chart:
    spec:
      chart: ./ops/helm-charts/metrics-calculation-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    mcs:
      cluster:
        scheduler:
          memory:
            limit: "90Gi"
            request: "85Gi"
        worker:
          threads: "16"
          memory:
            limit: "90Gi"
            request: "90Gi"