apiVersion: v1
kind: Namespace
metadata:
  name: base-agent
  labels:
    toolkit.fluxcd.io/tenant: apps
    ops.opensource.observer/environment: base
    kube-secrets-init.doit-intl.com/enable-mutation: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent
  namespace: base-agent
spec:
  chart:
    spec:
      chart: ./ops/helm-charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    app:
      name: "oso-agent"
      command: ["uv"]
      args:
        - run
        - --directory
        - warehouse/oso_agent
        - uvicorn
        - oso_agent.server.server:app
        - --host
        - 0.0.0.0
        - --port
        - 8080
      hostEnvVar: "AGENT_HOST"
      portEnvVar: "AGENT_PORT"
