from datetime import datetime

from metrics_tools.seed.types import Column, SeedConfig
from pydantic import BaseModel


class Sbom(BaseModel):
    artifact_namespace: str | None = Column("VARCHAR")
    artifact_name: str | None = Column("VARCHAR")
    artifact_source: str | None = Column("VARCHAR")
    package: str | None = Column("VARCHAR")
    package_source: str | None = Column("VARCHAR")
    package_version: str | None = Column("VARCHAR")
    snapshot_at: datetime | None = Column("TIMESTAMP(6) WITH TIME ZONE")
    dlt_load_id: str = Column("VARCHAR", column_name="_dlt_load_id")
    dlt_id: str = Column("VARCHAR", column_name="_dlt_id")


seed = SeedConfig(
    catalog="bigquery",
    schema="ossd",
    table="sbom",
    base=Sbom,
    rows=[
        Sbom(
            artifact_namespace="celo-org",
            artifact_name="op-geth",
            artifact_source="GITHUB",
            package="alpine/libssl3",
            package_source="APK",
            package_version="3.3.3-r0",
            snapshot_at=datetime.now(),
            dlt_load_id="1754681992.6715567",
            dlt_id="+dRl/jUK8biTmA",
        ),
        Sbom(
            artifact_namespace="consensus-shipyard",
            artifact_name="ipc",
            artifact_source="GITHUB",
            package="libp2p-swarm",
            package_source="CARGO",
            package_version="0.44.2",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="wmvV2K3gkjZ91g",
        ),
        Sbom(
            artifact_namespace="moztw",
            artifact_name="central",
            artifact_source="GITHUB",
            package="phpunit/phpunit",
            package_source="COMPOSER",
            package_version=">= 0",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="0UN8Ne3H9JYK8Q",
        ),
        Sbom(
            artifact_namespace="huggingface",
            artifact_name="text-generation-inference",
            artifact_source="GITHUB",
            package="cpp-9",
            package_source="DEB",
            package_version="9.4.0-1ubuntu1~20.04.2",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="ylRYcivQBNk9vQ",
        ),
        Sbom(
            artifact_namespace="w3c",
            artifact_name="wai-mobile",
            artifact_source="GITHUB",
            package="ruby2_keywords",
            package_source="GEM",
            package_version="0.0.5",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="Jm1lpgU5mIBZ+g",
        ),
        Sbom(
            artifact_namespace="leapdao",
            artifact_name="bridge-ui",
            artifact_source="GITHUB",
            package="com.github.leapdao/bridge-ui",
            package_source="GITHUB",
            package_version="master",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="sl3OJfO4pWi8LQ",
        ),
        Sbom(
            artifact_namespace="consensus-shipyard",
            artifact_name="ipc",
            artifact_source="GITHUB",
            package="Chizkiyahu/delete-untagged-ghcr-action",
            package_source="GITHUBACTIONS",
            package_version="3.*.*",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="x0c69UvMOd2qpQ",
        ),
        Sbom(
            artifact_namespace="celestiaorg",
            artifact_name="valuter",
            artifact_source="GITHUB",
            package="github.com/lib/pq",
            package_source="GOLANG",
            package_version="v1.10.6",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="8WjrMd9O0KH2pg",
        ),
        Sbom(
            artifact_namespace="google",
            artifact_name="java-sourcetools",
            artifact_source="GITHUB",
            package="com.google.javasourcetools:guava-patch",
            package_source="MAVEN",
            package_version="1.0",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="RAFs9ayAkIRhxw",
        ),
        Sbom(
            artifact_namespace="leapdao",
            artifact_name="bridge-ui",
            artifact_source="GITHUB",
            package="json-stringify-safe",
            package_source="NPM",
            package_version="5.0.1",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="lSzeSmeW5Q/z8w",
        ),
        Sbom(
            artifact_namespace="eBridgeCrosschain",
            artifact_name="ebridge-server-indexer",
            artifact_source="GITHUB",
            package="Orleans.Providers.MongoDB",
            package_source="NUGET",
            package_version="3.8.0",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="KLhIZqFHkA3nPg",
        ),
        Sbom(
            artifact_namespace="Huddle01",
            artifact_name="client-flutter-dart-example",
            artifact_source="GITHUB",
            package="meta",
            package_source="PUB",
            package_version="1.11.0",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="LOMdklgUQuFamw",
        ),
        Sbom(
            artifact_namespace="MuckRock",
            artifact_name="documentcloud-summarize-addon",
            artifact_source="GITHUB",
            package="spacy",
            package_source="PYPI",
            package_version=None,
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="OS+lR+i1OhWZ5g",
        ),
        Sbom(
            artifact_namespace="Planetable",
            artifact_name="PlanetClient",
            artifact_source="GITHUB",
            package="github.com/kylef/spectre",
            package_source="SWIFT",
            package_version="0.10.1",
            snapshot_at=datetime.now(),
            dlt_load_id="1755298789.7815282",
            dlt_id="/GHuBO0M1Pi/dw",
        ),
    ],
)
