# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data-model.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 2, "", "data-model.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x64\x61ta-model.proto"T\n\x13\x44\x61taModelRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\x0c\x12\x12\n\ndataset_id\x18\x02 \x01(\t\x12\x19\n\x11model_release_ids\x18\x03 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "data_model_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DATAMODELRUNREQUEST"]._serialized_start = 20
    _globals["_DATAMODELRUNREQUEST"]._serialized_end = 104
# @@protoc_insertion_point(module_scope)
