# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: publish-notebook.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 2, "", "publish-notebook.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16publish-notebook.proto"U\n\x19PublishNotebookRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\x0c\x12\x13\n\x0bnotebook_id\x18\x02 \x01(\t\x12\x13\n\x0boso_api_key\x18\x03 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "publish_notebook_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PUBLISHNOTEBOOKRUNREQUEST"]._serialized_start = 26
    _globals["_PUBLISHNOTEBOOKRUNREQUEST"]._serialized_end = 111
# @@protoc_insertion_point(module_scope)
