apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: production-nessie-cloudsql-proxy
spec:
  values:
    service:
      annotations:
        tailscale.com/expose: "true"
    cloudsql:
      instances:
        - instance: nessie-psql
          region: us-central1
          project: opensource-observer
          port: 5432