apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cloudsql-proxy
namespace: production-nessie-cloudsql-proxy
patches:
  - path: ./custom-helm-values.yaml
    target:
      kind: HelmRelease
    options:
      allowNameChange: true