# Generic worker executor. This is callable for use with cron scheduling.

# Execute the worker for a specific group
name: os-observer-indexer-worker
env:
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ vars.DB_DATABASE }}
  X_GITHUB_GRAPHQL_API: ${{ vars.X_GITHUB_GRAPHQL_API }}
  X_GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
  DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
  CACHE_DIR: /tmp/oso/cache
  RUN_DIR: /tmp/oso/run
  LOG_FILE: /tmp/oso/log/run.log

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      group:
        description: 'group'
        required: false
        default: 'none'
  # This workflow is reusable
  workflow_call:
    inputs:
      group:
        description: 'group'
        type: string
        required: false
        default: 'none'

jobs:
  collector-worker-call-manual:
    name: collector-worker-run-npm
    environment: indexer
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run worker
        uses: ./.github/workflows/indexer-worker
        with:
          group: ${{ inputs.group }}
          github_actor: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        